<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DelitosUsuariosSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('DELITO' => 'ABUSO DE AUTORIDAD', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'ABUSO DE CONFIANZA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ABUSO DE RETENCIÓN', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ABUSO SEXUAL', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'AMENAZAS - EJECUTADAS CON ARMA DE FUEGO, ARMA BLANCA U OBJETO CONTUNDENTE.', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'ALLANAMIENTO DE MORADA, EJECUTADO CON VIOLENCIA.', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'ATAQUES A LA VÍAS DE COMUNICACIÓN Y A LOS MEDIOS DE TRANSPORTE.', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'BIGAMIA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'COBRANZA ILEGITIMA.', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'CORRUPCIÓN', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'DAÑO EN PROPIEDAD AJENA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DAÑO EN PROPIEDAD AJENA AGRAVADO POR INCENDIO', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'DAÑO EN PROPIEDAD AJENA AGRAVADO POR EXPLOSIÓN', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'DAÑO EN PROPIEDAD AJENA CULPOSO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DELITOS CONTRA EL AMBIENTE', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DELITOS CONTRA LA INTIMIDAD Y LA IMAGEN', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'DELITOS CONTRA INVIOLABILIDAD DEL SECRETO Y DE LOS SISTEMAS Y EQUIPO DE COMPUTO Y PROTECCIÓN DE LOS DATOS PERSONALES', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DELITOS DE ABOGADOS', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DELITOS ELECTORALES', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'DESPOJO, EJECUTADO CON VIOLENCIA.', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'EXTORSIÓN', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'FALSEDAD ANTE LAS AUTORIDADES', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'FALSIFICACIÓN DE DOCUMENTOS', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'FALSIFICAR SELLOS, MARCAS, LLAVE U OTROS OBJETOS.', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'FRAUDE', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'FRAUDE PROCESAL', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'HOSTIGAMIENTO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'HOSTIGAMIENTO SEXUAL', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'INCESTO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'INCUMPLIMIENTO DE OBLIGACIONES DE ASISTENCIA FAMILIAR', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'INHUMACIÓN Y EXHUMACIÓN DE CADÁVERES', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'LESIONES', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'LESIONES CAUSADAS POR ANIMAL', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'LESIONES POR CULPA', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'LOCALIZACIÓN DE PERSONA', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'MALTRATO O CRUELDAD ANIMAL', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'OMISIÓN DE CUIDADO', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'PELIGRO DE CONTAGIO DE SALUD', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'PERSONA DESAPARECIDA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'PORNOGRAFÍA DE PERSONA MENOR DE 18 AÑOS', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'QUEBRANTAMIENTO DE SELLOS', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'RECEPCIÓN U OCULTACIÓN DE BIENES PRODUCTO DE UN DELITO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'RESPONSABILIDAD MÉDICA Y TÉCNICA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO CALIFICADO A CASA HABITACIÓN', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO CALIFICADO A LUGAR CERRADO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO CALIFICADO DE DEPENDIENTE', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO CON VIOELENCIA', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'ROBO DE VEHÍCULO', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'ROBO DE VEHÍCULO CON VIOLENCIA', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'SUSTRACCIÓN DE MENORES', 'IMPORTANCIA' => '2'),
			array('DELITO' => 'USO DE DOCUMENTOS FALSOS', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'USURPACIÓN DE FUNCIONES PÚBLICAS', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'USURPACIÓN DE PROFESIONES', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'SUPLANTACIÓN, USURPACIÓN DE IDENTIDAD.', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'VIOLACIÓN DE CORRESPONDENCIA', 'IMPORTANCIA' => '1'),
			array('DELITO' => 'VIOLENCIA FAMILIAR', 'IMPORTANCIA' => '2'),
		];
		$this->db->table('DELITOS_USUARIOS')->insertBatch($data);
	}
}
