<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class EmpleadosSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('EMPLEADOID' => '8926', 'NOMBRE' => 'ROSA MARÍA MAYORQUÍN MAYORQUÍN', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8927', 'NOMBRE' => 'GONZÁLEZ ESPAZRA YESENIA ISABEL', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8928', 'NOMBRE' => 'PARRA PIZARRO KARLA VANESSA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8929', 'NOMBRE' => 'OLVERA ALVAREZ ANA LUISA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8930', 'NOMBRE' => 'GARCÍA  ZAMORA JOSÉ DE JESÚS', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8931', 'NOMBRE' => 'GONZÁLEZ REYES CINTYA MAGALY', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8932', 'NOMBRE' => 'PAEZ VALENZUELA CLAUDIA YADIRA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8933', 'NOMBRE' => 'ACEBO GUTIERREZ CESAR HUMBERTO', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8934', 'NOMBRE' => 'PADILLA  CAMPOS JOSUE JOFIEL', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8935', 'NOMBRE' => 'DEL BOSQUE PARDO ALEJANDRO', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8936', 'NOMBRE' => 'TORRES ANDRADE LIZETH YAZMIN', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8937', 'NOMBRE' => 'VERDUGO QUEZADA ITZEL ALEJANDRA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8938', 'NOMBRE' => 'CORTEZ DURAN ISAIAS', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8939', 'NOMBRE' => 'LIRA CORONA ANDREA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8940', 'NOMBRE' => 'MEDEL RODRIGUEZ ISNA DANAHE', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8941', 'NOMBRE' => 'GONZÁLEZ RODRÍGUEZ JOSÉ RAMON', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8942', 'NOMBRE' => 'CRUZ REA FLOR MARBELLA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8943', 'NOMBRE' => 'CALDERA CAMPOS PATRICIA YANET', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8945', 'NOMBRE' => 'JOSÉ CERVANTES KIRK', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
			array('EMPLEADOID' => '8944', 'NOMBRE' => 'SONIA LÓPEZ URREA', 'PRIMERAPELLIDO' => '', 'SEGUNDOAPELLIDO' => '', 'OFICINAID' => '792', 'OFICINADESCR' => '', 'AREAID' => '3271', 'AREADESCR' => '', 'MUNICIPIOID' => 2, 'ESTADOID' => 2),
		];
		$this->db->table('EMPLEADOS')->insertBatch($data);
	}
}
