<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class HechoLugarSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('HECHOLUGARID' => 99, 'HECHODESCR' => 'OTROS'),
			array('HECHOLUGARID' => 10, 'HECHODESCR' => 'CAMINOS VECINALES'),
			array('HECHOLUGARID' => 6, 'HECHODESCR' => 'CARRETERAS ESTATALES'),
			array('HECHOLUGARID' => 66, 'HECHODESCR' => 'CARRETERAS FEDERALES'),
			array('HECHOLUGARID' => 1, 'HECHODESCR' => 'CASA HABITACION'),
			array('HECHOLUGARID' => 4, 'HECHODESCR' => 'CENTRO ESCOLAR'),
			array('HECHOLUGARID' => 11, 'HECHODESCR' => 'CENTRO RECREATIVO'),
			array('HECHOLUGARID' => 5, 'HECHODESCR' => 'CENTRO RELIGIOSO'),
			array('HECHOLUGARID' => 65, 'HECHODESCR' => 'CUENTA HABIENTE'),
			array('HECHOLUGARID' => 7, 'HECHODESCR' => 'DESPOBLADO'),
			array('HECHOLUGARID' => 18, 'HECHODESCR' => 'EN TRANSPORTE INDIVIDUAL'),
			array('HECHOLUGARID' => 19, 'HECHODESCR' => 'EN TRANSPORTE PUBLICO COLECTIVO'),
			array('HECHOLUGARID' => 20, 'HECHODESCR' => 'EN TRANSPORTE PUBLICO INDIVIDUAL'),
			array('HECHOLUGARID' => 14, 'HECHODESCR' => 'ESTACIONAMIENTOS'),
			array('HECHOLUGARID' => 15, 'HECHODESCR' => 'HOTEL'),
			array('HECHOLUGARID' => 9, 'HECHODESCR' => 'INSTITUCION BANCARIA'),
			array('HECHOLUGARID' => 3, 'HECHODESCR' => 'INSTITUCION PUBLICA'),
			array('HECHOLUGARID' => 12, 'HECHODESCR' => 'INSTITUCIONES PRIVADAS'),
			array('HECHOLUGARID' => 8, 'HECHODESCR' => 'LOCAL COMERCIAL'),
			array('HECHOLUGARID' => 13, 'HECHODESCR' => 'PUERTOS FEDERALES'),
			array('HECHOLUGARID' => 16, 'HECHODESCR' => 'TRANSEUNTE EN ESPACIO ABIERTO'),
			array('HECHOLUGARID' => 17, 'HECHODESCR' => 'TRANSPORTISTA'),
			array('HECHOLUGARID' => 2, 'HECHODESCR' => 'VIA PUBLICA'),
			array('HECHOLUGARID' => 30, 'HECHODESCR' => 'CAMINOS VECINALES (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 26, 'HECHODESCR' => 'CARRETERAS ESTATALES (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 63, 'HECHODESCR' => 'CARRETERAS FEDERALES (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 21, 'HECHODESCR' => 'CASA HABITACION (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 24, 'HECHODESCR' => 'CENTRO ESCOLAR (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 31, 'HECHODESCR' => 'CENTRO RECREATIVO (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 25, 'HECHODESCR' => 'CENTRO RELIGIOSO (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 41, 'HECHODESCR' => 'CUENTA HABIENTE (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 27, 'HECHODESCR' => 'DESPOBLADO (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 38, 'HECHODESCR' => 'EN TRANSPORTE INDIVIDUAL (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 39, 'HECHODESCR' => 'EN TRANSPORTE PUB. COLECTIVO (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 40, 'HECHODESCR' => 'EN TRANSPORTE PUB. INDIVIDUAL (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 34, 'HECHODESCR' => 'ESTACIONAMIENTOS (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 35, 'HECHODESCR' => 'HOTEL (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 29, 'HECHODESCR' => 'INSTITUCION BANCARIA (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 23, 'HECHODESCR' => 'INSTITUCION PUBLICA (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 32, 'HECHODESCR' => 'INSTITUCIONES PRIVADAS (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 28, 'HECHODESCR' => 'LOCAL COMERCIAL (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 33, 'HECHODESCR' => 'PUERTOS FEDERALES (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 36, 'HECHODESCR' => 'TRANSEUNTE EN ESPACIO ABIERTO (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 37, 'HECHODESCR' => 'TRANSPORTISTA (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 22, 'HECHODESCR' => 'VIA PUBLICA (CON ARMA DE FUEGO)'),
			array('HECHOLUGARID' => 51, 'HECHODESCR' => 'CAMINOS VECINALES (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 47, 'HECHODESCR' => 'CARRETERAS ESTATALES (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 64, 'HECHODESCR' => 'CARRETERAS FEDERALES (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 42, 'HECHODESCR' => 'CASA HABITACION (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 45, 'HECHODESCR' => 'CENTRO ESCOLAR  (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 52, 'HECHODESCR' => 'CENTRO RECREATIVO (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 46, 'HECHODESCR' => 'CENTRO RELIGIOSO (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 62, 'HECHODESCR' => 'CUENTA HABIENTE (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 48, 'HECHODESCR' => 'DESPOBLADO (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 59, 'HECHODESCR' => 'EN TRANSPORTE INDIVIDUAL (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 60, 'HECHODESCR' => 'EN TRANSPORTE PUBLICO COLECTIVO (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 61, 'HECHODESCR' => 'EN TRANSPORTE PUBLICO INDIVIDUAL (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 55, 'HECHODESCR' => 'ESTACIONAMIENTOS (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 56, 'HECHODESCR' => 'HOTEL (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 50, 'HECHODESCR' => 'INSTITUCION BANCARIA (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 44, 'HECHODESCR' => 'INSTITUCION PUBLICA  (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 53, 'HECHODESCR' => 'INSTITUCIONES PRIVADAS (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 49, 'HECHODESCR' => 'LOCAL COMERCIAL (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 54, 'HECHODESCR' => 'PUERTOS FEDERALES (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 57, 'HECHODESCR' => 'TRANSEUNTE EN ESPACIO ABIERTO (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 58, 'HECHODESCR' => 'TRANSPORTISTA (CON ARMA BLANCA)'),
			array('HECHOLUGARID' => 43, 'HECHODESCR' => 'VIA PUBLICA (CON ARMA BLANCA)'),
		];

		$this->db->table('HECHOLUGAR')->insertBatch($data);
	}
}
