<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class OficinaSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('OFICINAID' => '724', 'OFICINADESCR' => 'CENTRO DE JUSTICIA ALTERNATIVA ZONA ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '726', 'OFICINADESCR' => 'MODULO DE ORIENTACION CALLE NOVENA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '727', 'OFICINADESCR' => 'MODULO DE MEDIACION CALLE NOVENA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '728', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA  ORIENTACION PRADERAS DEL CIPRES', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '729', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA  MEDIACION PRADERAS DEL CIPRES', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '730', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA ORIENTACION SAN QUINTIN', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '731', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA  MEDIACION SAN QUINTIN', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '732', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA ORIENTACION MANEADERO', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '733', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA MEDIACION MANEADERO', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '2', 'OFICINADESCR' => 'CENTRO DE JUSTICIA ALTERNATIVA PENAL CJP (ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '3', 'OFICINADESCR' => 'CENTRO DE JUSTICIA ALTERNATIVA PENAL CJP (MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '4', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA ANAHUAC (ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '5', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA ANAHUAC (MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '7', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA CIAC ORIENTE(MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '268', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA  CIAC ORIENTE(ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '269', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA GUADALUPE VICTORIA  (ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '271', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA GUADALUPE VICTORIA  (MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '272', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA CIUDAD MORELOS  (ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '273', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA CIUDAD MORELOS  (MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '274', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA SAN FELIPE  (ORIENTACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '275', 'OFICINADESCR' => 'MODULO DE JUSTICIA ALTERNATIVA SAN FELIPE (MEDIACION)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '324', 'OFICINADESCR' => 'MODULO DE ORIENTACION TECATE', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '325', 'OFICINADESCR' => 'MODULO DE MEDIACION TECATE', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '804', 'OFICINADESCR' => 'MODULO DE ORIENTACION ZONA RIO', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '805', 'OFICINADESCR' => 'MODULO DE ORIENTACION LA MESA', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '806', 'OFICINADESCR' => 'MODULO DE MEDIACION ZONA RIO', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '807', 'OFICINADESCR' => 'MODULO DE MEDIACION LA MESA', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '863', 'OFICINADESCR' => 'MODULO DE ORIENTACION MARIANO MATAMOROS', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '864', 'OFICINADESCR' => 'MODULO DE MEDIACION MARIANO MATAMOROS', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '865', 'OFICINADESCR' => 'MODULO DE ORIENTACION PLAYAS DE ROSARITO', 'ESTADOID' => '2', 'MUNICIPIOID' => '5'),
			array('OFICINAID' => '866', 'OFICINADESCR' => 'MODULO DE MEDIACION PLAYAS DE ROSARITO', 'ESTADOID' => '2', 'MUNICIPIOID' => '5'),
		];
		$this->db->table("OFICINA")->insertBatch($data);
	}
}
