<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class OficinaTestingSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('OFICINAID' => '793', 'OFICINADESCR' => 'CDTEC - ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '394', 'OFICINADESCR' => 'CDTEC - MEXICALI', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '394', 'OFICINADESCR' => 'CDTEC - TECATE', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '924', 'OFICINADESCR' => 'CDTEC - TIJUANA', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
			array('OFICINAID' => '924', 'OFICINADESCR' => 'CDTEC - PLAYAS DE ROSARITO', 'ESTADOID' => '2', 'MUNICIPIOID' => '5'),

			//COORDINACIONES
			array('OFICINAID' => '701', 'OFICINADESCR' => 'COORDINACION CON DETENIDO ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '703', 'OFICINADESCR' => 'COORDINACION U.I. FORANEAS', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '709', 'OFICINADESCR' => 'COORDINACION DE ROBO  ', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '713', 'OFICINADESCR' => 'DIRECCION REGIONAL DE LA FISCALÍA ESPECIALIZADA DE DELITOS CONTRA LA VIDA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '715', 'OFICINADESCR' => 'COORDINACION DE U.I. SAN QUINTIN', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '717', 'OFICINADESCR' => 'COORDINACION DE DELITOS CONTRA EL PATRIMONIO Y LA SOC', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '719', 'OFICINADESCR' => 'COORDINACION UTMC', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '747', 'OFICINADESCR' => 'COORDINACION DE VISITADURIA ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '749', 'OFICINADESCR' => 'COORDINACION DE NARCOMENUDEO ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '753', 'OFICINADESCR' => 'COORDINACION DE TRATA DE PERSONAS ENSENADA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '770', 'OFICINADESCR' => 'COORDINACION ESTATAL DE ANTISECUESTROS', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '773', 'OFICINADESCR' => 'COORDINACION DE ROBO DE VEHICULOS', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '774', 'OFICINADESCR' => 'COORDINACION DE BUSQUEDA DE PERSONAS NO LOCALIZADAS', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '776', 'OFICINADESCR' => 'COORDINACION CONTRA LA LIBERTAD SEXUAL Y FAMILIAR', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '778', 'OFICINADESCR' => 'COORDINACION DE LA FISCALIA ESP. EN DELITOS DE TORTURA', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '781', 'OFICINADESCR' => 'COORD DE DELITOS DE PERSONAS Y SU LIBERTAD', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '787', 'OFICINADESCR' => 'COORDINACION DE LA UNIDAD DE DELITOS ELECTORALES', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '790', 'OFICINADESCR' => 'COORDINACION DE LA FISCALIA ESPECIAL DE LA FGE', 'ESTADOID' => '2', 'MUNICIPIOID' => '1'),
			array('OFICINAID' => '52', 'OFICINADESCR' => 'COORDINACION B - U.I. DE DELITOS CONTRA LAS PERSONAS Y SU LIBERTAD', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '53', 'OFICINADESCR' => 'COORDINACION C - U.I. DE DELITOS CONTRA LA LIBERTAD SEXUAL Y FAMILIA', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '54', 'OFICINADESCR' => 'COORDINACION D - U.I. DE DELITOS DE ROBO DE VEHICULO', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '55', 'OFICINADESCR' => 'COORDINACION E - U.I. DE DELITOS DE ROBO', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '57', 'OFICINADESCR' => 'COORDINACION F - U.I. DE DELITOS CONTRA EL PATRIMONIO, SOCIEDAD, ESTADO Y JUSTICIA', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '58', 'OFICINADESCR' => 'COORDINACION H - U.I. DE DELITOS CON DETENIDO ORIENTE', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '59', 'OFICINADESCR' => 'COORDINACION J (DELITOS COMETIDOS POR ADOLESCENTES)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '73', 'OFICINADESCR' => 'COORDINACION G - U.I. DE DELITOS CON DETENIDO PONIENTE', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '108', 'OFICINADESCR' => 'DIRECCION DE ASUNTOS INTERNOS', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '168', 'OFICINADESCR' => 'COORDINACION A - U.I. DE DELITOS CONTRA LA VIDA Y LA INTEGRIDAD', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '300', 'OFICINADESCR' => 'COORDINACION U - UTMC', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '308', 'OFICINADESCR' => 'COORDINACION K (GUADALUPE VICTORIA)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '309', 'OFICINADESCR' => 'COORD L (CIUDAD MORELOS)', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '310', 'OFICINADESCR' => 'COORDINACION N - SAN FELIPE', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '346', 'OFICINADESCR' => 'COORDINACION DE NARCOMENUDEO', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '374', 'OFICINADESCR' => 'COORDINACION DE DELITOS DE TRATA DE PERSONAS', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '382', 'OFICINADESCR' => 'COORDINACION CAPEA', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '386', 'OFICINADESCR' => 'COORDINACION DE LA FISCALIA ESP. EN DELITOS DE TORTURA', 'ESTADOID' => '2', 'MUNICIPIOID' => '2'),
			array('OFICINAID' => '312', 'OFICINADESCR' => 'COORDINACION DE DELITOS CON DETENIDO', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '316', 'OFICINADESCR' => 'COORDINACION DE DELITOS SIN DETENIDO TECATE, B.C.', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '389', 'OFICINADESCR' => 'COORDINACION DE LA FISCALIA ESP. EN DELITOS DE TORTURA ZONA TECATE', 'ESTADOID' => '2', 'MUNICIPIOID' => '3'),
			array('OFICINAID' => '876', 'OFICINADESCR' => 'JEFATURA DE VISITADURIA', 'ESTADOID' => '2', 'MUNICIPIOID' => '4'),
		];
		$this->db->table("OFICINA")->insertBatch($data);
	}
}
