<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PaisesSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('NAME' => 'Afganistán', 'ISO_2' => 'AF,', 'ISO_3' => 'AFG', 'PHONE_CODE' => '93'),
			array('NAME' => 'Albania', 'ISO_2' => 'AL,', 'ISO_3' => 'ALB', 'PHONE_CODE' => '355'),
			array('NAME' => 'Alemania', 'ISO_2' => 'DE,', 'ISO_3' => 'DEU', 'PHONE_CODE' => '49'),
			array('NAME' => 'Algeria', 'ISO_2' => 'DZ,', 'ISO_3' => 'DZA', 'PHONE_CODE' => '213'),
			array('NAME' => 'Andorra', 'ISO_2' => 'AD,', 'ISO_3' => 'AND', 'PHONE_CODE' => '376'),
			array('NAME' => 'Angola', 'ISO_2' => 'AO,', 'ISO_3' => 'AGO', 'PHONE_CODE' => '244'),
			array('NAME' => 'Anguila', 'ISO_2' => 'AI,', 'ISO_3' => 'AIA', 'PHONE_CODE' => '1 264'),
			array('NAME' => 'Antártida', 'ISO_2' => 'AQ,', 'ISO_3' => 'ATA', 'PHONE_CODE' => '672'),
			array('NAME' => 'Antigua y Barbuda', 'ISO_2' => 'AG,', 'ISO_3' => 'ATG', 'PHONE_CODE' => '1 268'),
			array('NAME' => 'Antillas Neerlandesas', 'ISO_2' => 'AN,', 'ISO_3' => 'ANT', 'PHONE_CODE' => '599'),
			array('NAME' => 'Arabia Saudita', 'ISO_2' => 'SA,', 'ISO_3' => 'SAU', 'PHONE_CODE' => '966'),
			array('NAME' => 'Argentina', 'ISO_2' => 'AR,', 'ISO_3' => 'ARG', 'PHONE_CODE' => '54'),
			array('NAME' => 'Armenia', 'ISO_2' => 'AM,', 'ISO_3' => 'ARM', 'PHONE_CODE' => '374'),
			array('NAME' => 'Aruba', 'ISO_2' => 'AW,', 'ISO_3' => 'ABW', 'PHONE_CODE' => '297'),
			array('NAME' => 'Australia', 'ISO_2' => 'AU,', 'ISO_3' => 'AUS', 'PHONE_CODE' => '61'),
			array('NAME' => 'Austria', 'ISO_2' => 'AT,', 'ISO_3' => 'AUT', 'PHONE_CODE' => '43'),
			array('NAME' => 'Azerbayán', 'ISO_2' => 'AZ,', 'ISO_3' => 'AZE', 'PHONE_CODE' => '994'),
			array('NAME' => 'Bahamas', 'ISO_2' => 'BS,', 'ISO_3' => 'BHS', 'PHONE_CODE' => '1 242'),
			array('NAME' => 'Bahrein', 'ISO_2' => 'BH,', 'ISO_3' => 'BHR', 'PHONE_CODE' => '973'),
			array('NAME' => 'Bangladesh', 'ISO_2' => 'BD,', 'ISO_3' => 'BGD', 'PHONE_CODE' => '880'),
			array('NAME' => 'Barbados', 'ISO_2' => 'BB,', 'ISO_3' => 'BRB', 'PHONE_CODE' => '1 246'),
			array('NAME' => 'Bélgica', 'ISO_2' => 'BE,', 'ISO_3' => 'BEL', 'PHONE_CODE' => '32'),
			array('NAME' => 'Belice', 'ISO_2' => 'BZ,', 'ISO_3' => 'BLZ', 'PHONE_CODE' => '501'),
			array('NAME' => 'Benín', 'ISO_2' => 'BJ,', 'ISO_3' => 'BEN', 'PHONE_CODE' => '229'),
			array('NAME' => 'Bhután', 'ISO_2' => 'BT,', 'ISO_3' => 'BTN', 'PHONE_CODE' => '975'),
			array('NAME' => 'Bielorrusia', 'ISO_2' => 'BY,', 'ISO_3' => 'BLR', 'PHONE_CODE' => '375'),
			array('NAME' => 'Birmania', 'ISO_2' => 'MM,', 'ISO_3' => 'MMR', 'PHONE_CODE' => '95'),
			array('NAME' => 'Bolivia', 'ISO_2' => 'BO,', 'ISO_3' => 'BOL', 'PHONE_CODE' => '591'),
			array('NAME' => 'Bosnia y Herzegovina', 'ISO_2' => 'BA,', 'ISO_3' => 'BIH', 'PHONE_CODE' => '387'),
			array('NAME' => 'Botsuana', 'ISO_2' => 'BW,', 'ISO_3' => 'BWA', 'PHONE_CODE' => '267'),
			array('NAME' => 'Brasil', 'ISO_2' => 'BR,', 'ISO_3' => 'BRA', 'PHONE_CODE' => '55'),
			array('NAME' => 'Brunéi', 'ISO_2' => 'BN,', 'ISO_3' => 'BRN', 'PHONE_CODE' => '673'),
			array('NAME' => 'Bulgaria', 'ISO_2' => 'BG,', 'ISO_3' => 'BGR', 'PHONE_CODE' => '359'),
			array('NAME' => 'Burkina Faso', 'ISO_2' => 'BF,', 'ISO_3' => 'BFA', 'PHONE_CODE' => '226'),
			array('NAME' => 'Burundi', 'ISO_2' => 'BI,', 'ISO_3' => 'BDI', 'PHONE_CODE' => '257'),
			array('NAME' => 'Cabo Verde', 'ISO_2' => 'CV,', 'ISO_3' => 'CPV', 'PHONE_CODE' => '238'),
			array('NAME' => 'Camboya', 'ISO_2' => 'KH,', 'ISO_3' => 'KHM', 'PHONE_CODE' => '855'),
			array('NAME' => 'Camerún', 'ISO_2' => 'CM,', 'ISO_3' => 'CMR', 'PHONE_CODE' => '237'),
			array('NAME' => 'Canadá', 'ISO_2' => 'CA,', 'ISO_3' => 'CAN', 'PHONE_CODE' => '1'),
			array('NAME' => 'Chad', 'ISO_2' => 'TD,', 'ISO_3' => 'TCD', 'PHONE_CODE' => '235'),
			array('NAME' => 'Chile', 'ISO_2' => 'CL,', 'ISO_3' => 'CHL', 'PHONE_CODE' => '56'),
			array('NAME' => 'China', 'ISO_2' => 'CN,', 'ISO_3' => 'CHN', 'PHONE_CODE' => '86'),
			array('NAME' => 'Chipre', 'ISO_2' => 'CY,', 'ISO_3' => 'CYP', 'PHONE_CODE' => '357'),
			array('NAME' => 'Ciudad del Vaticano', 'ISO_2' => 'VA,', 'ISO_3' => 'VAT', 'PHONE_CODE' => '39'),
			array('NAME' => 'Colombia', 'ISO_2' => 'CO,', 'ISO_3' => 'COL', 'PHONE_CODE' => '57'),
			array('NAME' => 'Comoras', 'ISO_2' => 'KM,', 'ISO_3' => 'COM', 'PHONE_CODE' => '269'),
			array('NAME' => 'Congo', 'ISO_2' => 'CG,', 'ISO_3' => 'COG', 'PHONE_CODE' => '242'),
			array('NAME' => 'Congo', 'ISO_2' => 'CD,', 'ISO_3' => 'COD', 'PHONE_CODE' => '243'),
			array('NAME' => 'Corea del Norte', 'ISO_2' => 'KP,', 'ISO_3' => 'PRK', 'PHONE_CODE' => '850'),
			array('NAME' => 'Corea del Sur', 'ISO_2' => 'KR,', 'ISO_3' => 'KOR', 'PHONE_CODE' => '82'),
			array('NAME' => 'Costa de Marfil', 'ISO_2' => 'CI,', 'ISO_3' => 'CIV', 'PHONE_CODE' => '225'),
			array('NAME' => 'Costa Rica', 'ISO_2' => 'CR,', 'ISO_3' => 'CRI', 'PHONE_CODE' => '506'),
			array('NAME' => 'Croacia', 'ISO_2' => 'HR,', 'ISO_3' => 'HRV', 'PHONE_CODE' => '385'),
			array('NAME' => 'Cuba', 'ISO_2' => 'CU,', 'ISO_3' => 'CUB', 'PHONE_CODE' => '53'),
			array('NAME' => 'Dinamarca', 'ISO_2' => 'DK,', 'ISO_3' => 'DNK', 'PHONE_CODE' => '45'),
			array('NAME' => 'Dominica', 'ISO_2' => 'DM,', 'ISO_3' => 'DMA', 'PHONE_CODE' => '1 767'),
			array('NAME' => 'Ecuador', 'ISO_2' => 'EC,', 'ISO_3' => 'ECU', 'PHONE_CODE' => '593'),
			array('NAME' => 'Egipto', 'ISO_2' => 'EG,', 'ISO_3' => 'EGY', 'PHONE_CODE' => '20'),
			array('NAME' => 'El Salvador', 'ISO_2' => 'SV,', 'ISO_3' => 'SLV', 'PHONE_CODE' => '503'),
			array('NAME' => 'Emiratos Árabes Unidos', 'ISO_2' => 'AE,', 'ISO_3' => 'ARE', 'PHONE_CODE' => '971'),
			array('NAME' => 'Eritrea', 'ISO_2' => 'ER,', 'ISO_3' => 'ERI', 'PHONE_CODE' => '291'),
			array('NAME' => 'Eslovaquia', 'ISO_2' => 'SK,', 'ISO_3' => 'SVK', 'PHONE_CODE' => '421'),
			array('NAME' => 'Eslovenia', 'ISO_2' => 'SI,', 'ISO_3' => 'SVN', 'PHONE_CODE' => '386'),
			array('NAME' => 'España', 'ISO_2' => 'ES,', 'ISO_3' => 'ESP', 'PHONE_CODE' => '34'),
			array('NAME' => 'Estados Unidos de América', 'ISO_2' => 'US,', 'ISO_3' => 'USA', 'PHONE_CODE' => '1'),
			array('NAME' => 'Estonia', 'ISO_2' => 'EE,', 'ISO_3' => 'EST', 'PHONE_CODE' => '372'),
			array('NAME' => 'Etiopía', 'ISO_2' => 'ET,', 'ISO_3' => 'ETH', 'PHONE_CODE' => '251'),
			array('NAME' => 'Filipinas', 'ISO_2' => 'PH,', 'ISO_3' => 'PHL', 'PHONE_CODE' => '63'),
			array('NAME' => 'Finlandia', 'ISO_2' => 'FI,', 'ISO_3' => 'FIN', 'PHONE_CODE' => '358'),
			array('NAME' => 'Fiyi', 'ISO_2' => 'FJ,', 'ISO_3' => 'FJI', 'PHONE_CODE' => '679'),
			array('NAME' => 'Francia', 'ISO_2' => 'FR,', 'ISO_3' => 'FRA', 'PHONE_CODE' => '33'),
			array('NAME' => 'Gabón', 'ISO_2' => 'GA,', 'ISO_3' => 'GAB', 'PHONE_CODE' => '241'),
			array('NAME' => 'Gambia', 'ISO_2' => 'GM,', 'ISO_3' => 'GMB', 'PHONE_CODE' => '220'),
			array('NAME' => 'Georgia', 'ISO_2' => 'GE,', 'ISO_3' => 'GEO', 'PHONE_CODE' => '995'),
			array('NAME' => 'Ghana', 'ISO_2' => 'GH,', 'ISO_3' => 'GHA', 'PHONE_CODE' => '233'),
			array('NAME' => 'Gibraltar', 'ISO_2' => 'GI,', 'ISO_3' => 'GIB', 'PHONE_CODE' => '350'),
			array('NAME' => 'Granada', 'ISO_2' => 'GD,', 'ISO_3' => 'GRD', 'PHONE_CODE' => '1 473'),
			array('NAME' => 'Grecia', 'ISO_2' => 'GR,', 'ISO_3' => 'GRC', 'PHONE_CODE' => '30'),
			array('NAME' => 'Groenlandia', 'ISO_2' => 'GL,', 'ISO_3' => 'GRL', 'PHONE_CODE' => '299'),
			array('NAME' => 'Guadalupe', 'ISO_2' => 'GP,', 'ISO_3' => 'GLP', 'PHONE_CODE' => ''),
			array('NAME' => 'Guam', 'ISO_2' => 'GU,', 'ISO_3' => 'GUM', 'PHONE_CODE' => '1 671'),
			array('NAME' => 'Guatemala', 'ISO_2' => 'GT,', 'ISO_3' => 'GTM', 'PHONE_CODE' => '502'),
			array('NAME' => 'Guayana Francesa', 'ISO_2' => 'GF,', 'ISO_3' => 'GUF', 'PHONE_CODE' => ''),
			array('NAME' => 'Guernsey', 'ISO_2' => 'GG,', 'ISO_3' => 'GGY', 'PHONE_CODE' => ''),
			array('NAME' => 'Guinea', 'ISO_2' => 'GN,', 'ISO_3' => 'GIN', 'PHONE_CODE' => '224'),
			array('NAME' => 'Guinea Ecuatorial', 'ISO_2' => 'GQ,', 'ISO_3' => 'GNQ', 'PHONE_CODE' => '240'),
			array('NAME' => 'Guinea-Bissau', 'ISO_2' => 'GW,', 'ISO_3' => 'GNB', 'PHONE_CODE' => '245'),
			array('NAME' => 'Guyana', 'ISO_2' => 'GY,', 'ISO_3' => 'GUY', 'PHONE_CODE' => '592'),
			array('NAME' => 'Haití', 'ISO_2' => 'HT,', 'ISO_3' => 'HTI', 'PHONE_CODE' => '509'),
			array('NAME' => 'Honduras', 'ISO_2' => 'HN,', 'ISO_3' => 'HND', 'PHONE_CODE' => '504'),
			array('NAME' => 'Hong kong', 'ISO_2' => 'HK,', 'ISO_3' => 'HKG', 'PHONE_CODE' => '852'),
			array('NAME' => 'Hungría', 'ISO_2' => 'HU,', 'ISO_3' => 'HUN', 'PHONE_CODE' => '36'),
			array('NAME' => 'India', 'ISO_2' => 'IN,', 'ISO_3' => 'IND', 'PHONE_CODE' => '91'),
			array('NAME' => 'Indonesia', 'ISO_2' => 'ID,', 'ISO_3' => 'IDN', 'PHONE_CODE' => '62'),
			array('NAME' => 'Irak', 'ISO_2' => 'IQ,', 'ISO_3' => 'IRQ', 'PHONE_CODE' => '964'),
			array('NAME' => 'Irán', 'ISO_2' => 'IR,', 'ISO_3' => 'IRN', 'PHONE_CODE' => '98'),
			array('NAME' => 'Irlanda', 'ISO_2' => 'IE,', 'ISO_3' => 'IRL', 'PHONE_CODE' => '353'),
			array('NAME' => 'Isla Bouvet', 'ISO_2' => 'BV,', 'ISO_3' => 'BVT', 'PHONE_CODE' => ''),
			array('NAME' => 'Isla de Man', 'ISO_2' => 'IM,', 'ISO_3' => 'IMN', 'PHONE_CODE' => '44'),
			array('NAME' => 'Isla de Navidad', 'ISO_2' => 'CX,', 'ISO_3' => 'CXR', 'PHONE_CODE' => '61'),
			array('NAME' => 'Isla Norfolk', 'ISO_2' => 'NF,', 'ISO_3' => 'NFK', 'PHONE_CODE' => ''),
			array('NAME' => 'Islandia', 'ISO_2' => 'IS,', 'ISO_3' => 'ISL', 'PHONE_CODE' => '354'),
			array('NAME' => 'Islas Bermudas', 'ISO_2' => 'BM,', 'ISO_3' => 'BMU', 'PHONE_CODE' => '1 441'),
			array('NAME' => 'Islas Caimán', 'ISO_2' => 'KY,', 'ISO_3' => 'CYM', 'PHONE_CODE' => '1 345'),
			array('NAME' => 'Islas Cocos (Keeling)', 'ISO_2' => 'CC,', 'ISO_3' => 'CCK', 'PHONE_CODE' => '61'),
			array('NAME' => 'Islas Cook', 'ISO_2' => 'CK,', 'ISO_3' => 'COK', 'PHONE_CODE' => '682'),
			array('NAME' => 'Islas de Åland', 'ISO_2' => 'AX,', 'ISO_3' => 'ALA', 'PHONE_CODE' => ''),
			array('NAME' => 'Islas Feroe', 'ISO_2' => 'FO,', 'ISO_3' => 'FRO', 'PHONE_CODE' => '298'),
			array('NAME' => 'Islas Georgias del Sur y Sandwich del Sur', 'ISO_2' => 'GS,', 'ISO_3' => 'SGS', 'PHONE_CODE' => ''),
			array('NAME' => 'Islas Heard y McDonald', 'ISO_2' => 'HM,', 'ISO_3' => 'HMD', 'PHONE_CODE' => ''),
			array('NAME' => 'Islas Maldivas', 'ISO_2' => 'MV,', 'ISO_3' => 'MDV', 'PHONE_CODE' => '960'),
			array('NAME' => 'Islas Malvinas', 'ISO_2' => 'FK,', 'ISO_3' => 'FLK', 'PHONE_CODE' => '500'),
			array('NAME' => 'Islas Marianas del Norte', 'ISO_2' => 'MP,', 'ISO_3' => 'MNP', 'PHONE_CODE' => '1 670'),
			array('NAME' => 'Islas Marshall', 'ISO_2' => 'MH,', 'ISO_3' => 'MHL', 'PHONE_CODE' => '692'),
			array('NAME' => 'Islas Pitcairn', 'ISO_2' => 'PN,', 'ISO_3' => 'PCN', 'PHONE_CODE' => '870'),
			array('NAME' => 'Islas Salomón', 'ISO_2' => 'SB,', 'ISO_3' => 'SLB', 'PHONE_CODE' => '677'),
			array('NAME' => 'Islas Turcas y Caicos', 'ISO_2' => 'TC,', 'ISO_3' => 'TCA', 'PHONE_CODE' => '1 649'),
			array('NAME' => 'Islas Ultramarinas Menores de Estados Unidos', 'ISO_2' => 'UM,', 'ISO_3' => 'UMI', 'PHONE_CODE' => ''),
			array('NAME' => 'Islas Vírgenes Británicas', 'ISO_2' => 'VG,', 'ISO_3' => 'VG', 'PHONE_CODE' => '1 284'),
			array('NAME' => 'Islas Vírgenes de los Estados Unidos', 'ISO_2' => 'VI,', 'ISO_3' => 'VIR', 'PHONE_CODE' => '1 340'),
			array('NAME' => 'Israel', 'ISO_2' => 'IL,', 'ISO_3' => 'ISR', 'PHONE_CODE' => '972'),
			array('NAME' => 'Italia', 'ISO_2' => 'IT,', 'ISO_3' => 'ITA', 'PHONE_CODE' => '39'),
			array('NAME' => 'Jamaica', 'ISO_2' => 'JM,', 'ISO_3' => 'JAM', 'PHONE_CODE' => '1 876'),
			array('NAME' => 'Japón', 'ISO_2' => 'JP,', 'ISO_3' => 'JPN', 'PHONE_CODE' => '81'),
			array('NAME' => 'Jersey', 'ISO_2' => 'JE,', 'ISO_3' => 'JEY', 'PHONE_CODE' => ''),
			array('NAME' => 'Jordania', 'ISO_2' => 'JO,', 'ISO_3' => 'JOR', 'PHONE_CODE' => '962'),
			array('NAME' => 'Kazajistán', 'ISO_2' => 'KZ,', 'ISO_3' => 'KAZ', 'PHONE_CODE' => '7'),
			array('NAME' => 'Kenia', 'ISO_2' => 'KE,', 'ISO_3' => 'KEN', 'PHONE_CODE' => '254'),
			array('NAME' => 'Kirgizstán', 'ISO_2' => 'KG,', 'ISO_3' => 'KGZ', 'PHONE_CODE' => '996'),
			array('NAME' => 'Kiribati', 'ISO_2' => 'KI,', 'ISO_3' => 'KIR', 'PHONE_CODE' => '686'),
			array('NAME' => 'Kuwait', 'ISO_2' => 'KW,', 'ISO_3' => 'KWT', 'PHONE_CODE' => '965'),
			array('NAME' => 'Laos', 'ISO_2' => 'LA,', 'ISO_3' => 'LAO', 'PHONE_CODE' => '856'),
			array('NAME' => 'Lesoto', 'ISO_2' => 'LS,', 'ISO_3' => 'LSO', 'PHONE_CODE' => '266'),
			array('NAME' => 'Letonia', 'ISO_2' => 'LV,', 'ISO_3' => 'LVA', 'PHONE_CODE' => '371'),
			array('NAME' => 'Líbano', 'ISO_2' => 'LB,', 'ISO_3' => 'LBN', 'PHONE_CODE' => '961'),
			array('NAME' => 'Liberia', 'ISO_2' => 'LR,', 'ISO_3' => 'LBR', 'PHONE_CODE' => '231'),
			array('NAME' => 'Libia', 'ISO_2' => 'LY,', 'ISO_3' => 'LBY', 'PHONE_CODE' => '218'),
			array('NAME' => 'Liechtenstein', 'ISO_2' => 'LI,', 'ISO_3' => 'LIE', 'PHONE_CODE' => '423'),
			array('NAME' => 'Lituania', 'ISO_2' => 'LT,', 'ISO_3' => 'LTU', 'PHONE_CODE' => '370'),
			array('NAME' => 'Luxemburgo', 'ISO_2' => 'LU,', 'ISO_3' => 'LUX', 'PHONE_CODE' => '352'),
			array('NAME' => 'Macao', 'ISO_2' => 'MO,', 'ISO_3' => 'MAC', 'PHONE_CODE' => '853'),
			array('NAME' => 'Macedônia', 'ISO_2' => 'MK,', 'ISO_3' => 'MKD', 'PHONE_CODE' => '389'),
			array('NAME' => 'Madagascar', 'ISO_2' => 'MG,', 'ISO_3' => 'MDG', 'PHONE_CODE' => '261'),
			array('NAME' => 'Malasia', 'ISO_2' => 'MY,', 'ISO_3' => 'MYS', 'PHONE_CODE' => '60'),
			array('NAME' => 'Malawi', 'ISO_2' => 'MW,', 'ISO_3' => 'MWI', 'PHONE_CODE' => '265'),
			array('NAME' => 'Mali', 'ISO_2' => 'ML,', 'ISO_3' => 'MLI', 'PHONE_CODE' => '223'),
			array('NAME' => 'Malta', 'ISO_2' => 'MT,', 'ISO_3' => 'MLT', 'PHONE_CODE' => '356'),
			array('NAME' => 'Marruecos', 'ISO_2' => 'MA,', 'ISO_3' => 'MAR', 'PHONE_CODE' => '212'),
			array('NAME' => 'Martinica', 'ISO_2' => 'MQ,', 'ISO_3' => 'MTQ', 'PHONE_CODE' => ''),
			array('NAME' => 'Mauricio', 'ISO_2' => 'MU,', 'ISO_3' => 'MUS', 'PHONE_CODE' => '230'),
			array('NAME' => 'Mauritania', 'ISO_2' => 'MR,', 'ISO_3' => 'MRT', 'PHONE_CODE' => '222'),
			array('NAME' => 'Mayotte', 'ISO_2' => 'YT,', 'ISO_3' => 'MYT', 'PHONE_CODE' => '262'),
			array('NAME' => 'México', 'ISO_2' => 'MX,', 'ISO_3' => 'MEX', 'PHONE_CODE' => '52'),
			array('NAME' => 'Micronesia', 'ISO_2' => 'FM,', 'ISO_3' => 'FSM', 'PHONE_CODE' => '691'),
			array('NAME' => 'Moldavia', 'ISO_2' => 'MD,', 'ISO_3' => 'MDA', 'PHONE_CODE' => '373'),
			array('NAME' => 'Mónaco', 'ISO_2' => 'MC,', 'ISO_3' => 'MCO', 'PHONE_CODE' => '377'),
			array('NAME' => 'Mongolia', 'ISO_2' => 'MN,', 'ISO_3' => 'MNG', 'PHONE_CODE' => '976'),
			array('NAME' => 'Montenegro', 'ISO_2' => 'ME,', 'ISO_3' => 'MNE', 'PHONE_CODE' => '382'),
			array('NAME' => 'Montserrat', 'ISO_2' => 'MS,', 'ISO_3' => 'MSR', 'PHONE_CODE' => '1 664'),
			array('NAME' => 'Mozambique', 'ISO_2' => 'MZ,', 'ISO_3' => 'MOZ', 'PHONE_CODE' => '258'),
			array('NAME' => 'Namibia', 'ISO_2' => 'NA,', 'ISO_3' => 'NAM', 'PHONE_CODE' => '264'),
			array('NAME' => 'Nauru', 'ISO_2' => 'NR,', 'ISO_3' => 'NRU', 'PHONE_CODE' => '674'),
			array('NAME' => 'Nepal', 'ISO_2' => 'NP,', 'ISO_3' => 'NPL', 'PHONE_CODE' => '977'),
			array('NAME' => 'Nicaragua', 'ISO_2' => 'NI,', 'ISO_3' => 'NIC', 'PHONE_CODE' => '505'),
			array('NAME' => 'Niger', 'ISO_2' => 'NE,', 'ISO_3' => 'NER', 'PHONE_CODE' => '227'),
			array('NAME' => 'Nigeria', 'ISO_2' => 'NG,', 'ISO_3' => 'NGA', 'PHONE_CODE' => '234'),
			array('NAME' => 'Niue', 'ISO_2' => 'NU,', 'ISO_3' => 'NIU', 'PHONE_CODE' => '683'),
			array('NAME' => 'Noruega', 'ISO_2' => 'NO,', 'ISO_3' => 'NOR', 'PHONE_CODE' => '47'),
			array('NAME' => 'Nueva Caledonia', 'ISO_2' => 'NC,', 'ISO_3' => 'NCL', 'PHONE_CODE' => '687'),
			array('NAME' => 'Nueva Zelanda', 'ISO_2' => 'NZ,', 'ISO_3' => 'NZL', 'PHONE_CODE' => '64'),
			array('NAME' => 'Omán', 'ISO_2' => 'OM,', 'ISO_3' => 'OMN', 'PHONE_CODE' => '968'),
			array('NAME' => 'Países Bajos', 'ISO_2' => 'NL,', 'ISO_3' => 'NLD', 'PHONE_CODE' => '31'),
			array('NAME' => 'Pakistán', 'ISO_2' => 'PK,', 'ISO_3' => 'PAK', 'PHONE_CODE' => '92'),
			array('NAME' => 'Palau', 'ISO_2' => 'PW,', 'ISO_3' => 'PLW', 'PHONE_CODE' => '680'),
			array('NAME' => 'Palestina', 'ISO_2' => 'PS,', 'ISO_3' => 'PSE', 'PHONE_CODE' => ''),
			array('NAME' => 'Panamá', 'ISO_2' => 'PA,', 'ISO_3' => 'PAN', 'PHONE_CODE' => '507'),
			array('NAME' => 'Papúa Nueva Guinea', 'ISO_2' => 'PG,', 'ISO_3' => 'PNG', 'PHONE_CODE' => '675'),
			array('NAME' => 'Paraguay', 'ISO_2' => 'PY,', 'ISO_3' => 'PRY', 'PHONE_CODE' => '595'),
			array('NAME' => 'Perú', 'ISO_2' => 'PE,', 'ISO_3' => 'PER', 'PHONE_CODE' => '51'),
			array('NAME' => 'Polinesia Francesa', 'ISO_2' => 'PF,', 'ISO_3' => 'PYF', 'PHONE_CODE' => '689'),
			array('NAME' => 'Polonia', 'ISO_2' => 'PL,', 'ISO_3' => 'POL', 'PHONE_CODE' => '48'),
			array('NAME' => 'Portugal', 'ISO_2' => 'PT,', 'ISO_3' => 'PRT', 'PHONE_CODE' => '351'),
			array('NAME' => 'Puerto Rico', 'ISO_2' => 'PR,', 'ISO_3' => 'PRI', 'PHONE_CODE' => '1'),
			array('NAME' => 'Qatar', 'ISO_2' => 'QA,', 'ISO_3' => 'QAT', 'PHONE_CODE' => '974'),
			array('NAME' => 'Reino Unido', 'ISO_2' => 'GB,', 'ISO_3' => 'GBR', 'PHONE_CODE' => '44'),
			array('NAME' => 'República Centroafricana', 'ISO_2' => 'CF,', 'ISO_3' => 'CAF', 'PHONE_CODE' => '236'),
			array('NAME' => 'República Checa', 'ISO_2' => 'CZ,', 'ISO_3' => 'CZE', 'PHONE_CODE' => '420'),
			array('NAME' => 'República Dominicana', 'ISO_2' => 'DO,', 'ISO_3' => 'DOM', 'PHONE_CODE' => '1 809'),
			array('NAME' => 'Reunión', 'ISO_2' => 'RE,', 'ISO_3' => 'REU', 'PHONE_CODE' => ''),
			array('NAME' => 'Ruanda', 'ISO_2' => 'RW,', 'ISO_3' => 'RWA', 'PHONE_CODE' => '250'),
			array('NAME' => 'Rumanía', 'ISO_2' => 'RO,', 'ISO_3' => 'ROU', 'PHONE_CODE' => '40'),
			array('NAME' => 'Rusia', 'ISO_2' => 'RU,', 'ISO_3' => 'RUS', 'PHONE_CODE' => '7'),
			array('NAME' => 'Sahara Occidental', 'ISO_2' => 'EH,', 'ISO_3' => 'ESH', 'PHONE_CODE' => ''),
			array('NAME' => 'Samoa', 'ISO_2' => 'WS,', 'ISO_3' => 'WSM', 'PHONE_CODE' => '685'),
			array('NAME' => 'Samoa Americana', 'ISO_2' => 'AS,', 'ISO_3' => 'ASM', 'PHONE_CODE' => '1 684'),
			array('NAME' => 'San Bartolomé', 'ISO_2' => 'BL,', 'ISO_3' => 'BLM', 'PHONE_CODE' => '590'),
			array('NAME' => 'San Cristóbal y Nieves', 'ISO_2' => 'KN,', 'ISO_3' => 'KNA', 'PHONE_CODE' => '1 869'),
			array('NAME' => 'San Marino', 'ISO_2' => 'SM,', 'ISO_3' => 'SMR', 'PHONE_CODE' => '378'),
			array('NAME' => 'San Martín (Francia)', 'ISO_2' => 'MF,', 'ISO_3' => 'MAF', 'PHONE_CODE' => '1 599'),
			array('NAME' => 'San Pedro y Miquelón', 'ISO_2' => 'PM,', 'ISO_3' => 'SPM', 'PHONE_CODE' => '508'),
			array('NAME' => 'San Vicente y las Granadinas', 'ISO_2' => 'VC,', 'ISO_3' => 'VCT', 'PHONE_CODE' => '1 784'),
			array('NAME' => 'Santa Elena', 'ISO_2' => 'SH,', 'ISO_3' => 'SHN', 'PHONE_CODE' => '290'),
			array('NAME' => 'Santa Lucía', 'ISO_2' => 'LC,', 'ISO_3' => 'LCA', 'PHONE_CODE' => '1 758'),
			array('NAME' => 'Santo Tomé y Príncipe', 'ISO_2' => 'ST,', 'ISO_3' => 'STP', 'PHONE_CODE' => '239'),
			array('NAME' => 'Senegal', 'ISO_2' => 'SN,', 'ISO_3' => 'SEN', 'PHONE_CODE' => '221'),
			array('NAME' => 'Serbia', 'ISO_2' => 'RS,', 'ISO_3' => 'SRB', 'PHONE_CODE' => '381'),
			array('NAME' => 'Seychelles', 'ISO_2' => 'SC,', 'ISO_3' => 'SYC', 'PHONE_CODE' => '248'),
			array('NAME' => 'Sierra Leona', 'ISO_2' => 'SL,', 'ISO_3' => 'SLE', 'PHONE_CODE' => '232'),
			array('NAME' => 'Singapur', 'ISO_2' => 'SG,', 'ISO_3' => 'SGP', 'PHONE_CODE' => '65'),
			array('NAME' => 'Siria', 'ISO_2' => 'SY,', 'ISO_3' => 'SYR', 'PHONE_CODE' => '963'),
			array('NAME' => 'Somalia', 'ISO_2' => 'SO,', 'ISO_3' => 'SOM', 'PHONE_CODE' => '252'),
			array('NAME' => 'Sri lanka', 'ISO_2' => 'LK,', 'ISO_3' => 'LKA', 'PHONE_CODE' => '94'),
			array('NAME' => 'Sudáfrica', 'ISO_2' => 'ZA,', 'ISO_3' => 'ZAF', 'PHONE_CODE' => '27'),
			array('NAME' => 'Sudán', 'ISO_2' => 'SD,', 'ISO_3' => 'SDN', 'PHONE_CODE' => '249'),
			array('NAME' => 'Suecia', 'ISO_2' => 'SE,', 'ISO_3' => 'SWE', 'PHONE_CODE' => '46'),
			array('NAME' => 'Suiza', 'ISO_2' => 'CH,', 'ISO_3' => 'CHE', 'PHONE_CODE' => '41'),
			array('NAME' => 'Surinám', 'ISO_2' => 'SR,', 'ISO_3' => 'SUR', 'PHONE_CODE' => '597'),
			array('NAME' => 'Svalbard y Jan Mayen', 'ISO_2' => 'SJ,', 'ISO_3' => 'SJM', 'PHONE_CODE' => ''),
			array('NAME' => 'Swazilandia', 'ISO_2' => 'SZ,', 'ISO_3' => 'SWZ', 'PHONE_CODE' => '268'),
			array('NAME' => 'Tadjikistán', 'ISO_2' => 'TJ,', 'ISO_3' => 'TJK', 'PHONE_CODE' => '992'),
			array('NAME' => 'Tailandia', 'ISO_2' => 'TH,', 'ISO_3' => 'THA', 'PHONE_CODE' => '66'),
			array('NAME' => 'Taiwán', 'ISO_2' => 'TW,', 'ISO_3' => 'TWN', 'PHONE_CODE' => '886'),
			array('NAME' => 'Tanzania', 'ISO_2' => 'TZ,', 'ISO_3' => 'TZA', 'PHONE_CODE' => '255'),
			array('NAME' => 'Territorio Británico del Océano Índico', 'ISO_2' => 'IO,', 'ISO_3' => 'IOT', 'PHONE_CODE' => ''),
			array('NAME' => 'Territorios Australes y Antárticas Franceses', 'ISO_2' => 'TF,', 'ISO_3' => 'ATF', 'PHONE_CODE' => ''),
			array('NAME' => 'Timor Oriental', 'ISO_2' => 'TL,', 'ISO_3' => 'TLS', 'PHONE_CODE' => '670'),
			array('NAME' => 'Togo', 'ISO_2' => 'TG,', 'ISO_3' => 'TGO', 'PHONE_CODE' => '228'),
			array('NAME' => 'Tokelau', 'ISO_2' => 'TK,', 'ISO_3' => 'TKL', 'PHONE_CODE' => '690'),
			array('NAME' => 'Tonga', 'ISO_2' => 'TO,', 'ISO_3' => 'TON', 'PHONE_CODE' => '676'),
			array('NAME' => 'Trinidad y Tobago', 'ISO_2' => 'TT,', 'ISO_3' => 'TTO', 'PHONE_CODE' => '1 868'),
			array('NAME' => 'Tunez', 'ISO_2' => 'TN,', 'ISO_3' => 'TUN', 'PHONE_CODE' => '216'),
			array('NAME' => 'Turkmenistán', 'ISO_2' => 'TM,', 'ISO_3' => 'TKM', 'PHONE_CODE' => '993'),
			array('NAME' => 'Turquía', 'ISO_2' => 'TR,', 'ISO_3' => 'TUR', 'PHONE_CODE' => '90'),
			array('NAME' => 'Tuvalu', 'ISO_2' => 'TV,', 'ISO_3' => 'TUV', 'PHONE_CODE' => '688'),
			array('NAME' => 'Ucrania', 'ISO_2' => 'UA,', 'ISO_3' => 'UKR', 'PHONE_CODE' => '380'),
			array('NAME' => 'Uganda', 'ISO_2' => 'UG,', 'ISO_3' => 'UGA', 'PHONE_CODE' => '256'),
			array('NAME' => 'Uruguay', 'ISO_2' => 'UY,', 'ISO_3' => 'URY', 'PHONE_CODE' => '598'),
			array('NAME' => 'Uzbekistán', 'ISO_2' => 'UZ,', 'ISO_3' => 'UZB', 'PHONE_CODE' => '998'),
			array('NAME' => 'Vanuatu', 'ISO_2' => 'VU,', 'ISO_3' => 'VUT', 'PHONE_CODE' => '678'),
			array('NAME' => 'Venezuela', 'ISO_2' => 'VE,', 'ISO_3' => 'VEN', 'PHONE_CODE' => '58'),
			array('NAME' => 'Vietnam', 'ISO_2' => 'VN,', 'ISO_3' => 'VNM', 'PHONE_CODE' => '84'),
			array('NAME' => 'Wallis y Futuna', 'ISO_2' => 'WF,', 'ISO_3' => 'WLF', 'PHONE_CODE' => '681'),
			array('NAME' => 'Yemen', 'ISO_2' => 'YE,', 'ISO_3' => 'YEM', 'PHONE_CODE' => '967'),
			array('NAME' => 'Yibuti', 'ISO_2' => 'DJ,', 'ISO_3' => 'DJI', 'PHONE_CODE' => '253'),
			array('NAME' => 'Zambia', 'ISO_2' => 'ZM,', 'ISO_3' => 'ZMB', 'PHONE_CODE' => '260'),
			array('NAME' => 'Zimbabue', 'ISO_2' => 'ZW,', 'ISO_3' => 'ZWE', 'PHONE_CODE' => '263')
		];
		$this->db->table('PAISES')->insertBatch($data);
	}
}
