<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonaMoralGiroSeeder extends Seeder
{
    public function run()
    {
        $data = [
			array('PERSONAMORALGIROID' => '1', 'PERSONAMORALGIRODESCR' => 'SOCIEDAD CIVIL'),
            array('PERSONAMORALGIROID' => '2', 'PERSONAMORALGIRODESCR' => 'SOCIEDAD ANONIMA'),
			array('PERSONAMORALGIROID' => '3', 'PERSONAMORALGIRODESCR' => 'SOCIEDAD DE RESPONSABILIDAD LIMITADA'),
			array('PERSONAMORALGIROID' => '4', 'PERSONAMORALGIRODESCR' => 'SOCIEDAD COOPERATIVA'),
			array('PERSONAMORALGIROID' => '5', 'PERSONAMORALGIRODESCR' => 'ASOCIACION CIVIL'),
			array('PERSONAMORALGIROID' => '6', 'PERSONAMORALGIRODESCR' => 'ORGNISMO DESCENTRALIZADO'),
			array('PERSONAMORALGIROID' => '7', 'PERSONAMORALGIRODESCR' => 'INSTITUCIONES DE CREDITO'),
			array('PERSONAMORALGIROID' => '8', 'PERSONAMORALGIRODESCR' => 'GOBIERNO'),
			array('PERSONAMORALGIROID' => '9', 'PERSONAMORALGIRODESCR' => 'OTRA'),

        ];
		$this->db->table('PERSONAMORALGIRO')->insertBatch($data);
    }
}
