<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonaEdoCivilSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('PERSONAESTADOCIVILID' => 1, 'PERSONAESTADOCIVILDESCR' => 'CASADO'),
			array('PERSONAESTADOCIVILID' => 2, 'PERSONAESTADOCIVILDESCR' => 'UNION LIBRE'),
			array('PERSONAESTADOCIVILID' => 3, 'PERSONAESTADOCIVILDESCR' => 'DIVORCIADO'),
			array('PERSONAESTADOCIVILID' => 4, 'PERSONAESTADOCIVILDESCR' => 'SEPARADO'),
			array('PERSONAESTADOCIVILID' => 5, 'PERSONAESTADOCIVILDESCR' => 'VIUDO'),
			array('PERSONAESTADOCIVILID' => 6, 'PERSONAESTADOCIVILDESCR' => 'SOLTERO'),
			array('PERSONAESTADOCIVILID' => 9, 'PERSONAESTADOCIVILDESCR' => 'NO ESPECIFICADO'),
		];

		$this->db->table('CATEGORIA_PERSONAEDOCIVIL')->insertBatch($data);
	}
}
