<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonaTipoIdentificacionSeeder extends Seeder
{
    public function run()
    {
        $data = [
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CARTA DE NATURALIZACION', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CARTILLA DE SERVICIO MILITAR', 'FORMATOCAPTURA' => '#######', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{7}$'),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CLAVE UNICA DE REGISTRO DE POBLACION (CURP)', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CEDULA PROFESIONAL', 'FORMATOCAPTURA' => '#######', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{7}$'),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL EMPLEO GOBIERNO', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DE ELECTOR', 'FORMATOCAPTURA' => '#############', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^(\d{10}|\d{13})$'),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DE ESTUDIANTE', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL IMSS', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL INSEN', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL ISSSTE', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'LICENCIA DE CONDUCTOR', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'PASAPORTE', 'FORMATOCAPTURA' => '###########', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{11}$'),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CERTIFICADO ESCOLAR', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'BOLETA DE CALIFICACIONES', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'TARJETA BANCARIA', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'GAFETE', 'FORMATOCAPTURA' => '###########', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CONSTANCIA DE ESTUDIOS', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL ISSSTEP', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
            array('PERSONATIPOIDENTIFICACIONDESCR' => 'NINGUNA', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),

        ];
        $this->db->table('CATEGORIA_PERSONATIPOIDENTIFICACION')->insertBatch($data);
    }
}
