<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonaCalidadJuridicaSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('PERSONACALIDADJURIDICAID' => 1, 'PERSONACALIDADJURIDICADESCR' => 'OFENDIDO', 'COMPORTAMIENTO' => 'VIC'),
			array('PERSONACALIDADJURIDICAID' => 2, 'PERSONACALIDADJURIDICADESCR' => 'IMPUTADO', 'COMPORTAMIENTO' => 'IMP'),
			array('PERSONACALIDADJURIDICAID' => 3, 'PERSONACALIDADJURIDICADESCR' => 'TESTIGO', 'COMPORTAMIENTO' => 'TEST'),
			array('PERSONACALIDADJURIDICAID' => 4, 'PERSONACALIDADJURIDICADESCR' => 'TERCERO', 'COMPORTAMIENTO' => 'TER'),
			array('PERSONACALIDADJURIDICAID' => 5, 'PERSONACALIDADJURIDICADESCR' => 'REPRESENTANTE LEGAL', 'COMPORTAMIENTO' => 'TER'),
			array('PERSONACALIDADJURIDICAID' => 6, 'PERSONACALIDADJURIDICADESCR' => 'VICTIMA', 'COMPORTAMIENTO' => 'VIC'),
			array('PERSONACALIDADJURIDICAID' => 10, 'PERSONACALIDADJURIDICADESCR' => 'COMPARECIENTE', 'COMPORTAMIENTO' => 'VIC'),
		];

		$this->db->table('PERSONACALIDADJURIDICA')->insertBatch($data);
	}
}
