<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonaTipoIdentificacionSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('PERSONATIPOIDENTIFICACIONID' => '1', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CARTA DE NATURALIZACION', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '2', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CARTILLA DE SERVICIO MILITAR', 'FORMATOCAPTURA' => '#######', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{7}$'),
			array('PERSONATIPOIDENTIFICACIONID' => '3', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CLAVE UNICA DE REGISTRO DE POBLACION (CURP)', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '4', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CEDULA PROFESIONAL', 'FORMATOCAPTURA' => '#######', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{7}$'),
			array('PERSONATIPOIDENTIFICACIONID' => '5', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL EMPLEO GOBIERNO', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '6', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DE ELECTOR', 'FORMATOCAPTURA' => '#############', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^(\d{10}|\d{13})$'),
			array('PERSONATIPOIDENTIFICACIONID' => '7', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DE ESTUDIANTE', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '8', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL IMSS', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '9', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL INSEN', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '10', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL ISSSTE', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '11', 'PERSONATIPOIDENTIFICACIONDESCR' => 'LICENCIA DE CONDUCTOR', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '12', 'PERSONATIPOIDENTIFICACIONDESCR' => 'PASAPORTE', 'FORMATOCAPTURA' => '###########', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => '^\d{11}$'),
			array('PERSONATIPOIDENTIFICACIONID' => '13', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CERTIFICADO ESCOLAR', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '14', 'PERSONATIPOIDENTIFICACIONDESCR' => 'BOLETA DE CALIFICACIONES', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '15', 'PERSONATIPOIDENTIFICACIONDESCR' => 'TARJETA BANCARIA', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '16', 'PERSONATIPOIDENTIFICACIONDESCR' => 'GAFETE', 'FORMATOCAPTURA' => '###########', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '17', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CONSTANCIA DE ESTUDIOS', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '18', 'PERSONATIPOIDENTIFICACIONDESCR' => 'CREDENCIAL DEL ISSSTEP', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),
			array('PERSONATIPOIDENTIFICACIONID' => '999', 'PERSONATIPOIDENTIFICACIONDESCR' => 'NINGUNA', 'FORMATOCAPTURA' => '', 'IDENTIFICACIONPREDETERMINADA' => '', 'EXPRESIONREGULAR' => ''),

		];
		$this->db->table('CATEGORIA_PERSONATIPOIDENTIFICACION')->insertBatch($data);
	}
}
