<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TipoExpedienteSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('TIPOEXPEDIENTEID' => 1, 'TIPOEXPEDIENTEDESCR' => '(NUC) CASO DE INVESTIGACION', 'TIPOEXPEDIENTECLAVE' => 'NUC', 'EDOJURIDICOIMPINICIALID' => '1', 'PERMITECONCLUIR' => 'S'),
			array('TIPOEXPEDIENTEID' => 4, 'TIPOEXPEDIENTEDESCR' => '(NAC) ACTA CIRCUNSTANCIADA', 'TIPOEXPEDIENTECLAVE' => 'NAC', 'EDOJURIDICOIMPINICIALID' => '1', 'PERMITECONCLUIR' => 'S'),
			array('TIPOEXPEDIENTEID' => 5, 'TIPOEXPEDIENTEDESCR' => '(RAC) REGISTRO DE ATENCION CIUDADANA', 'TIPOEXPEDIENTECLAVE' => 'RAC', 'EDOJURIDICOIMPINICIALID' => '4', 'PERMITECONCLUIR' => 'N'),
			array('TIPOEXPEDIENTEID' => 6, 'TIPOEXPEDIENTEDESCR' => '(EXH) EXHORTO', 'TIPOEXPEDIENTECLAVE' => 'EXH', 'EDOJURIDICOIMPINICIALID' => '1', 'PERMITECONCLUIR' => 'S'),
			array('TIPOEXPEDIENTEID' => 7, 'TIPOEXPEDIENTEDESCR' => '(NAV) ATENCION A VICTIMAS DEL DELITO', 'TIPOEXPEDIENTECLAVE' => 'NUV', 'EDOJURIDICOIMPINICIALID' => '1', 'PERMITECONCLUIR' => 'N'),
			array('TIPOEXPEDIENTEID' => 8, 'TIPOEXPEDIENTEDESCR' => '(NCE) CONSTANCIA DE EXTRAVIO', 'TIPOEXPEDIENTECLAVE' => 'NCE', 'EDOJURIDICOIMPINICIALID' => '4', 'PERMITECONCLUIR' => 'N'),
			array('TIPOEXPEDIENTEID' => 9, 'TIPOEXPEDIENTEDESCR' => '(NUI) NUMERO UNICO DE INVESTIGACION', 'TIPOEXPEDIENTECLAVE' => 'NUI', 'EDOJURIDICOIMPINICIALID' => '1', 'PERMITECONCLUIR' => 'S'),
		];
		$this->db->table('TIPOEXPEDIENTE')->insertBatch($data);
	}
}
