<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class VehiculoPaisSeeder extends Seeder
{
    public function run()
    {
        $data = [
            array('PAISID' => '1', 'PAISDESCR' => 'AFGANISTÃN'),
            array('PAISID' => '2', 'PAISDESCR' => 'ALBANIA'),
            array('PAISID' => '3', 'PAISDESCR' => 'ALEMANIA'),
            array('PAISID' => '4', 'PAISDESCR' => 'AMERICAN SAMOA'),
            array('PAISID' => '5', 'PAISDESCR' => 'ANDORRA'),
            array('PAISID' => '6', 'PAISDESCR' => 'ANGOLA'),
            array('PAISID' => '7', 'PAISDESCR' => 'ANGUILA'),
            array('PAISID' => '8', 'PAISDESCR' => 'ANTIGUA AND BARBUDA'),
            array('PAISID' => '9', 'PAISDESCR' => 'ANTILLAS HOLANDESAS'),
            array('PAISID' => '10', 'PAISDESCR' => 'ANTÃRTIDA'),
            array('PAISID' => '11', 'PAISDESCR' => 'ARABIA SAUDITA'),
            array('PAISID' => '12', 'PAISDESCR' => 'ARGELIA'),
            array('PAISID' => '13', 'PAISDESCR' => 'ARGENTINA'),
            array('PAISID' => '14', 'PAISDESCR' => 'ARMENIA'),
            array('PAISID' => '15', 'PAISDESCR' => 'ARUBA'),
            array('PAISID' => '17', 'PAISDESCR' => 'AUSTRALIA'),
            array('PAISID' => '18', 'PAISDESCR' => 'AUSTRIA'),
            array('PAISID' => '19', 'PAISDESCR' => 'AZERBAIJAN'),
            array('PAISID' => '20', 'PAISDESCR' => 'BAHAMAS'),
            array('PAISID' => '21', 'PAISDESCR' => 'BAHREIN'),
            array('PAISID' => '22', 'PAISDESCR' => 'BANGLADESH'),
            array('PAISID' => '23', 'PAISDESCR' => 'BARBADOS'),
            array('PAISID' => '24', 'PAISDESCR' => 'BELICE'),
            array('PAISID' => '25', 'PAISDESCR' => 'BENIN'),
            array('PAISID' => '26', 'PAISDESCR' => 'BERMUDA'),
            array('PAISID' => '27', 'PAISDESCR' => 'BIELORRUSIA'),
            array('PAISID' => '28', 'PAISDESCR' => 'BOLIVIA'),
            array('PAISID' => '29', 'PAISDESCR' => 'BOSNIA Y HERZEGOVINA'),
            array('PAISID' => '30', 'PAISDESCR' => 'BOTSUANA'),
            array('PAISID' => '31', 'PAISDESCR' => 'BOUVET ISLAND'),
            array('PAISID' => '32', 'PAISDESCR' => 'BRASIL'),
            array('PAISID' => '33', 'PAISDESCR' => 'BRITISH INDIAN OCEAN TERRITORY'),
            array('PAISID' => '34', 'PAISDESCR' => 'BRUNEI DARUSSALAM'),
            array('PAISID' => '35', 'PAISDESCR' => 'BULGARIA'),
            array('PAISID' => '36', 'PAISDESCR' => 'BURKINA FASO'),
            array('PAISID' => '37', 'PAISDESCR' => 'BURUNDI'),
            array('PAISID' => '38', 'PAISDESCR' => 'BUTÃN'),
            array('PAISID' => '39', 'PAISDESCR' => 'BÃ‰LGICA'),
            array('PAISID' => '40', 'PAISDESCR' => 'CABO VERDA'),
            array('PAISID' => '41', 'PAISDESCR' => 'CAMBOYA'),
            array('PAISID' => '42', 'PAISDESCR' => 'CAMERÃšN'),
            array('PAISID' => '44', 'PAISDESCR' => 'CANADÃ'),
            array('PAISID' => '45', 'PAISDESCR' => 'CHAD'),
            array('PAISID' => '46', 'PAISDESCR' => 'CHILE'),
            array('PAISID' => '47', 'PAISDESCR' => 'CHINA'),
            array('PAISID' => '48', 'PAISDESCR' => 'CHIPRE'),
            array('PAISID' => '49', 'PAISDESCR' => 'COLOMBIA'),
            array('PAISID' => '50', 'PAISDESCR' => 'COMORES'),
            array('PAISID' => '51', 'PAISDESCR' => 'CONGO'),
            array('PAISID' => '52', 'PAISDESCR' => 'COREA DEL NORTE'),
            array('PAISID' => '53', 'PAISDESCR' => 'COREA DEL SUR'),
            array('PAISID' => '54', 'PAISDESCR' => 'COSTA RICA'),
            array('PAISID' => '55', 'PAISDESCR' => 'COTE D IVOIRE'),
            array('PAISID' => '56', 'PAISDESCR' => 'CROACIA'),
            array('PAISID' => '57', 'PAISDESCR' => 'CUBA'),
            array('PAISID' => '58', 'PAISDESCR' => 'DINAMARCA'),
            array('PAISID' => '59', 'PAISDESCR' => 'DJIBOUTI'),
            array('PAISID' => '60', 'PAISDESCR' => 'DOMINICA'),
            array('PAISID' => '61', 'PAISDESCR' => 'EAST TIMOR'),
            array('PAISID' => '62', 'PAISDESCR' => 'ECUADOR'),
            array('PAISID' => '63', 'PAISDESCR' => 'EGIPTO'),
            array('PAISID' => '64', 'PAISDESCR' => 'EL SALVADOR'),
            array('PAISID' => '65', 'PAISDESCR' => 'EL VATICANO'),
            array('PAISID' => '66', 'PAISDESCR' => 'EMIRATOS ARABES UNIDOS'),
            array('PAISID' => '67', 'PAISDESCR' => 'ERITREA'),
            array('PAISID' => '68', 'PAISDESCR' => 'ESLOVAQUIA'),
            array('PAISID' => '69', 'PAISDESCR' => 'ESLOVENIA'),
            array('PAISID' => '70', 'PAISDESCR' => 'ESPAÃ‘A'),
            array('PAISID' => '71', 'PAISDESCR' => 'ESTADOS UNIDOS'),
            array('PAISID' => '72', 'PAISDESCR' => 'ESTONIA'),
            array('PAISID' => '73', 'PAISDESCR' => 'ETIOPÃA'),
            array('PAISID' => '74', 'PAISDESCR' => 'FIJI'),
            array('PAISID' => '75', 'PAISDESCR' => 'FILIPINAS'),
            array('PAISID' => '76', 'PAISDESCR' => 'FINLANDIA'),
            array('PAISID' => '77', 'PAISDESCR' => 'FRANCIA'),
            array('PAISID' => '78', 'PAISDESCR' => 'FRENCH GUIANA'),
            array('PAISID' => '79', 'PAISDESCR' => 'FRENCH POLYNESIA'),
            array('PAISID' => '80', 'PAISDESCR' => 'FRENCH SOUTHERN TERRITORIES'),
            array('PAISID' => '81', 'PAISDESCR' => 'GABÃ“N'),
            array('PAISID' => '82', 'PAISDESCR' => 'GAMBIA'),
            array('PAISID' => '83', 'PAISDESCR' => 'GEORGIA'),
            array('PAISID' => '84', 'PAISDESCR' => 'GHANA'),
            array('PAISID' => '85', 'PAISDESCR' => 'GIBRALTAR'),
            array('PAISID' => '86', 'PAISDESCR' => 'GRANADA'),
            array('PAISID' => '87', 'PAISDESCR' => 'GRECIA'),
            array('PAISID' => '88', 'PAISDESCR' => 'GROENLANDIA'),
            array('PAISID' => '89', 'PAISDESCR' => 'GUADALUPE'),
            array('PAISID' => '90', 'PAISDESCR' => 'GUAM'),
            array('PAISID' => '91', 'PAISDESCR' => 'GUATEMALA'),
            array('PAISID' => '92', 'PAISDESCR' => 'GUINEA'),
            array('PAISID' => '93', 'PAISDESCR' => 'GUINEA ECUATORIAL'),
            array('PAISID' => '94', 'PAISDESCR' => 'GUINEA-BISSAU'),
            array('PAISID' => '95', 'PAISDESCR' => 'GUYANA'),
            array('PAISID' => '96', 'PAISDESCR' => 'HAITÃ'),
            array('PAISID' => '97', 'PAISDESCR' => 'HEARD ISLAND AND MCDONALD ISLA'),
            array('PAISID' => '98', 'PAISDESCR' => 'HOLANDA'),
            array('PAISID' => '99', 'PAISDESCR' => 'HONDURAS'),
            array('PAISID' => '100', 'PAISDESCR' => 'HONG KONG'),
            array('PAISID' => '101', 'PAISDESCR' => 'HUNGRÃA'),
            array('PAISID' => '102', 'PAISDESCR' => 'INDIA'),
            array('PAISID' => '103', 'PAISDESCR' => 'INDONESIA'),
            array('PAISID' => '104', 'PAISDESCR' => 'IRAQ'),
            array('PAISID' => '105', 'PAISDESCR' => 'IRLANDA'),
            array('PAISID' => '106', 'PAISDESCR' => 'ISALAS COCOS'),
            array('PAISID' => '107', 'PAISDESCR' => 'ISLA CHRISTMAS'),
            array('PAISID' => '108', 'PAISDESCR' => 'ISLANDIA'),
            array('PAISID' => '109', 'PAISDESCR' => 'ISLAS CAIMÃN'),
            array('PAISID' => '110', 'PAISDESCR' => 'ISLAS COOK'),
            array('PAISID' => '111', 'PAISDESCR' => 'ISLAS FEROE'),
            array('PAISID' => '112', 'PAISDESCR' => 'ISLAS MALVINAS'),
            array('PAISID' => '113', 'PAISDESCR' => 'ISLAS MARSHALL'),
            array('PAISID' => '114', 'PAISDESCR' => 'ISLAS MAURICIO'),
            array('PAISID' => '115', 'PAISDESCR' => 'ISLAS SALOMÃ“N'),
            array('PAISID' => '116', 'PAISDESCR' => 'ISLAS SANDWHICH'),
            array('PAISID' => '117', 'PAISDESCR' => 'ISLAS TURKS Y CAICOS'),
            array('PAISID' => '118', 'PAISDESCR' => 'ISLAS WALLIS Y FUTUNA'),
            array('PAISID' => '119', 'PAISDESCR' => 'ISRAEL'),
            array('PAISID' => '120', 'PAISDESCR' => 'ITALIA'),
            array('PAISID' => '121', 'PAISDESCR' => 'JAMAICA'),
            array('PAISID' => '122', 'PAISDESCR' => 'JAPÃ“N'),
            array('PAISID' => '123', 'PAISDESCR' => 'JORDANIA'),
            array('PAISID' => '124', 'PAISDESCR' => 'KAZAKHSTÃN'),
            array('PAISID' => '125', 'PAISDESCR' => 'KENIA'),
            array('PAISID' => '126', 'PAISDESCR' => 'KIRIBATI'),
            array('PAISID' => '127', 'PAISDESCR' => 'KUWAIT'),
            array('PAISID' => '128', 'PAISDESCR' => 'KYRGYZSTÃN'),
            array('PAISID' => '129', 'PAISDESCR' => 'LAOS'),
            array('PAISID' => '130', 'PAISDESCR' => 'LATVIA'),
            array('PAISID' => '131', 'PAISDESCR' => 'LESOTO'),
            array('PAISID' => '132', 'PAISDESCR' => 'LIBERIA'),
            array('PAISID' => '133', 'PAISDESCR' => 'LIBIA'),
            array('PAISID' => '134', 'PAISDESCR' => 'LIECHTENSTEIN'),
            array('PAISID' => '135', 'PAISDESCR' => 'LITUANIA'),
            array('PAISID' => '136', 'PAISDESCR' => 'LUXEMBURGO'),
            array('PAISID' => '137', 'PAISDESCR' => 'LÃBANO'),
            array('PAISID' => '138', 'PAISDESCR' => 'MACAO'),
            array('PAISID' => '139', 'PAISDESCR' => 'MACEDONIA'),
            array('PAISID' => '140', 'PAISDESCR' => 'MADAGASCAR'),
            array('PAISID' => '141', 'PAISDESCR' => 'MALASIA'),
            array('PAISID' => '142', 'PAISDESCR' => 'MALAUI'),
            array('PAISID' => '143', 'PAISDESCR' => 'MALDIVAS'),
            array('PAISID' => '144', 'PAISDESCR' => 'MALTA'),
            array('PAISID' => '145', 'PAISDESCR' => 'MALÃ'),
            array('PAISID' => '146', 'PAISDESCR' => 'MARRUECOS'),
            array('PAISID' => '147', 'PAISDESCR' => 'MARTINIQUE'),
            array('PAISID' => '148', 'PAISDESCR' => 'MAURITANIA'),
            array('PAISID' => '149', 'PAISDESCR' => 'MAYOTTE'),
            array('PAISID' => '150', 'PAISDESCR' => 'MICRONESIA'),
            array('PAISID' => '151', 'PAISDESCR' => 'MOLDAVIA'),
            array('PAISID' => '152', 'PAISDESCR' => 'MONGOLIA'),
            array('PAISID' => '153', 'PAISDESCR' => 'MONTSERRAT'),
            array('PAISID' => '154', 'PAISDESCR' => 'MOZAMBIQUE'),
            array('PAISID' => '155', 'PAISDESCR' => 'MYANMAR'),
            array('PAISID' => '156', 'PAISDESCR' => 'MÃ‰XICO'),
            array('PAISID' => '157', 'PAISDESCR' => 'MÃ“NACO'),
            array('PAISID' => '158', 'PAISDESCR' => 'NAMIBIA'),
            array('PAISID' => '159', 'PAISDESCR' => 'NAURU'),
            array('PAISID' => '160', 'PAISDESCR' => 'NEPAL'),
            array('PAISID' => '161', 'PAISDESCR' => 'NICARAGUA'),
            array('PAISID' => '162', 'PAISDESCR' => 'NIGERIA'),
            array('PAISID' => '163', 'PAISDESCR' => 'NIUE'),
            array('PAISID' => '164', 'PAISDESCR' => 'NORFOLK ISLAND'),
            array('PAISID' => '165', 'PAISDESCR' => 'NORTHERN MARIANA ISLANDS'),
            array('PAISID' => '166', 'PAISDESCR' => 'NORUEGA'),
            array('PAISID' => '167', 'PAISDESCR' => 'NUEVA CALEDONIA'),
            array('PAISID' => '168', 'PAISDESCR' => 'NUEVA ZELANDA'),
            array('PAISID' => '169', 'PAISDESCR' => 'NÃGER'),
            array('PAISID' => '170', 'PAISDESCR' => 'OMÃN'),
            array('PAISID' => '171', 'PAISDESCR' => 'PAKISTÃN'),
            array('PAISID' => '172', 'PAISDESCR' => 'PALAU'),
            array('PAISID' => '173', 'PAISDESCR' => 'PALESTINIAN TERRITORY'),
            array('PAISID' => '174', 'PAISDESCR' => 'PANAMÃ'),
            array('PAISID' => '175', 'PAISDESCR' => 'PAPÃšA NUEVA GUINEA'),
            array('PAISID' => '176', 'PAISDESCR' => 'PARAGUAY'),
            array('PAISID' => '177', 'PAISDESCR' => 'PERÃš'),
            array('PAISID' => '178', 'PAISDESCR' => 'PITCAIRN'),
            array('PAISID' => '179', 'PAISDESCR' => 'POLONIA'),
            array('PAISID' => '180', 'PAISDESCR' => 'PORTUGAL'),
            array('PAISID' => '181', 'PAISDESCR' => 'PUERTO RICO'),
            array('PAISID' => '182', 'PAISDESCR' => 'QATAR'),
            array('PAISID' => '183', 'PAISDESCR' => 'REINO UNIDO'),
            array('PAISID' => '184', 'PAISDESCR' => 'REPÃšBLICA CENTROAFRICANA'),
            array('PAISID' => '185', 'PAISDESCR' => 'REPÃšBLICA CHECA'),
            array('PAISID' => '186', 'PAISDESCR' => 'REPÃšBLICA DEMOCRÃTICA DEL CONG'),
            array('PAISID' => '187', 'PAISDESCR' => 'REPÃšBLICA DOMINICANA'),
            array('PAISID' => '188', 'PAISDESCR' => 'REPÃšBLICA ISLÃMICA DE IRÃN'),
            array('PAISID' => '189', 'PAISDESCR' => 'RUANDA'),
            array('PAISID' => '190', 'PAISDESCR' => 'RUMANIA'),
            array('PAISID' => '191', 'PAISDESCR' => 'RUSIAN'),
            array('PAISID' => '192', 'PAISDESCR' => 'SAINT KITTS AND NEVIS'),
            array('PAISID' => '193', 'PAISDESCR' => 'SAINT PIERRE Y MIQUELON'),
            array('PAISID' => '194', 'PAISDESCR' => 'SAMOA'),
            array('PAISID' => '195', 'PAISDESCR' => 'SAN MARINO'),
            array('PAISID' => '196', 'PAISDESCR' => 'SAN VICENTE Y LAS GRANADINAS'),
            array('PAISID' => '197', 'PAISDESCR' => 'SANTA ELENA'),
            array('PAISID' => '198', 'PAISDESCR' => 'SANTA LUCÃA'),
            array('PAISID' => '199', 'PAISDESCR' => 'SAO TOME AND PRINCIPE'),
            array('PAISID' => '200', 'PAISDESCR' => 'SENEGAL'),
            array('PAISID' => '201', 'PAISDESCR' => 'SERBIA Y MONTENEGRO'),
            array('PAISID' => '202', 'PAISDESCR' => 'SEYCHELLES'),
            array('PAISID' => '203', 'PAISDESCR' => 'SIERRA LEONA'),
            array('PAISID' => '204', 'PAISDESCR' => 'SINGAPUR'),
            array('PAISID' => '205', 'PAISDESCR' => 'SIRIA'),
            array('PAISID' => '206', 'PAISDESCR' => 'SOMALÃA'),
            array('PAISID' => '207', 'PAISDESCR' => 'SRI LANKA'),
            array('PAISID' => '208', 'PAISDESCR' => 'SUAZILANDIA'),
            array('PAISID' => '209', 'PAISDESCR' => 'SUDÃFRICA'),
            array('PAISID' => '210', 'PAISDESCR' => 'SUDÃN'),
            array('PAISID' => '211', 'PAISDESCR' => 'SUECIA'),
            array('PAISID' => '212', 'PAISDESCR' => 'SUIZA'),
            array('PAISID' => '213', 'PAISDESCR' => 'SURINAM'),
            array('PAISID' => '214', 'PAISDESCR' => 'SVALBARD AND JAN MAYEN'),
            array('PAISID' => '215', 'PAISDESCR' => 'TAILANDIA'),
            array('PAISID' => '216', 'PAISDESCR' => 'TAIWAN'),
            array('PAISID' => '217', 'PAISDESCR' => 'TAJIKISTÃN'),
            array('PAISID' => '218', 'PAISDESCR' => 'TANZANIA'),
            array('PAISID' => '219', 'PAISDESCR' => 'TOGO'),
            array('PAISID' => '220', 'PAISDESCR' => 'TONGA'),
            array('PAISID' => '221', 'PAISDESCR' => 'TOQUELAU'),
            array('PAISID' => '222', 'PAISDESCR' => 'TRINIDAD Y TOBAGO'),
            array('PAISID' => '223', 'PAISDESCR' => 'TURKMENISTÃN'),
            array('PAISID' => '224', 'PAISDESCR' => 'TURQUÃA'),
            array('PAISID' => '225', 'PAISDESCR' => 'TUVALU'),
            array('PAISID' => '226', 'PAISDESCR' => 'TÃšNEZ'),
            array('PAISID' => '227', 'PAISDESCR' => 'UCRANIA'),
            array('PAISID' => '228', 'PAISDESCR' => 'UGANDA'),
            array('PAISID' => '229', 'PAISDESCR' => 'UNITED STATES MINOR OUTLYING I'),
            array('PAISID' => '230', 'PAISDESCR' => 'URUGUAY'),
            array('PAISID' => '231', 'PAISDESCR' => 'UZBEKISTAN'),
            array('PAISID' => '232', 'PAISDESCR' => 'VANUATU'),
            array('PAISID' => '233', 'PAISDESCR' => 'VENEZUELA'),
            array('PAISID' => '234', 'PAISDESCR' => 'VIETNAM'),
            array('PAISID' => '235', 'PAISDESCR' => 'VIRGIN ISLANDS BRITISH'),
            array('PAISID' => '236', 'PAISDESCR' => 'VIRGIN ISLANDS U.S.'),
            array('PAISID' => '237', 'PAISDESCR' => 'WESTERN SAHARA'),
            array('PAISID' => '238', 'PAISDESCR' => 'YEMEN'),
            array('PAISID' => '239', 'PAISDESCR' => 'ZAIRE'),
            array('PAISID' => '240', 'PAISDESCR' => 'ZAMBIA'),
            array('PAISID' => '241', 'PAISDESCR' => 'ZIMBABUE'),

        ];
        $this->db->table('VEHICULOPAIS')->insertBatch($data);
    }
}
