<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class VehiculoColorSeeder extends Seeder
{
	public function run()
	{
		$data = [
			array('VEHICULOCOLORID'=>'1','VEHICULOCOLORDESCR' => 'CAFE'),
			array('VEHICULOCOLORID'=>'2','VEHICULOCOLORDESCR' => 'BLANCO'),
			array('VEHICULOCOLORID'=>'3','VEHICULOCOLORDESCR' => 'AZUL'),
			array('VEHICULOCOLORID'=>'4','VEHICULOCOLORDESCR' => 'GUINDA'),
			array('VEHICULOCOLORID'=>'5','VEHICULOCOLORDESCR' => 'NEGRO'),
			array('VEHICULOCOLORID'=>'6','VEHICULOCOLORDESCR' => 'DORADO'),
			array('VEHICULOCOLORID'=>'7','VEHICULOCOLORDESCR' => 'VERDE'),
			array('VEHICULOCOLORID'=>'8','VEHICULOCOLORDESCR' => 'AMARILLO'),
			array('VEHICULOCOLORID'=>'9','VEHICULOCOLORDESCR' => 'MORADO'),
			array('VEHICULOCOLORID'=>'10','VEHICULOCOLORDESCR' => 'GRIS'),
			array('VEHICULOCOLORID'=>'11','VEHICULOCOLORDESCR' => 'ROJO'),
			array('VEHICULOCOLORID'=>'12','VEHICULOCOLORDESCR' => 'ANARANJADO'),
			array('VEHICULOCOLORID'=>'13','VEHICULOCOLORDESCR' => 'ROSA'),
			array('VEHICULOCOLORID'=>'14','VEHICULOCOLORDESCR' => 'MARRON'),
			array('VEHICULOCOLORID'=>'15','VEHICULOCOLORDESCR' => 'PLATEADO'),
			array('VEHICULOCOLORID'=>'16','VEHICULOCOLORDESCR' => 'CREMA'),
			array('VEHICULOCOLORID'=>'17','VEHICULOCOLORDESCR' => 'ALMENDRA'),
			array('VEHICULOCOLORID'=>'18','VEHICULOCOLORDESCR' => 'ZAFIRO'),
			array('VEHICULOCOLORID'=>'19','VEHICULOCOLORDESCR' => 'PEWTER'),
			array('VEHICULOCOLORID'=>'20','VEHICULOCOLORDESCR' => 'CASTAÑO'),
			array('VEHICULOCOLORID'=>'21','VEHICULOCOLORDESCR' => 'BRONCE'),
			array('VEHICULOCOLORID'=>'22','VEHICULOCOLORDESCR' => 'AZUL MARINO'),
			array('VEHICULOCOLORID'=>'23','VEHICULOCOLORDESCR' => 'MULTIPLES COLORES'),
			array('VEHICULOCOLORID'=>'24','VEHICULOCOLORDESCR' => 'ARENA'),
			array('VEHICULOCOLORID'=>'99','VEHICULOCOLORDESCR' => 'OTRO'),

		];
		$this->db->table('VEHICULOCOLOR')->insertBatch($data);
	}
}
