<?php

namespace App\Models;

use CodeIgniter\Model;

class ConstanciaExtravioModel extends Model
{
	protected $DBGroup          = 'default';
	protected $table            = 'CONSTANCIAEXTRAVIO';
	protected $allowedFields    = [
		'CONSTANCIAEXTRAVIOID',
		'ANO',
		'SOLICITANTEID',
		'MUNICIPIOID',
		'MUNICIPIOIDCITA',
		'ESTADOID',
		'EXTRAVIO',
		'DOMICILIO',
		'HECHOLUGARID',
		'HECHOFECHA',
		'PLACEHOLDER',
		'NBOLETO',
		'NTALON',
		'NOMBRESORTEO',
		'SORTEOFECHA',
		'PERMISOGOBERNACION',
		'PERMISOGOBCOLABORADORES',
		'TIPODOCUMENTO',
		'NDOCUMENTO',
		'DUENONOMBREDOC',
		'DUENOAPELLIDOPDOC',
		'DUENOAPELLIDOMDOC',
		'SERIEVEHICULO',
		'NPLACA',
		'POSICIONPLACA',
		'DISTRIBUIDORVEHICULO',
		'MARCA',
		'MODELO',
		'ANIOVEHICULO',
		'AGENTEID',
		'NUMEROIDENTIFICADOR',
		'RAZONSOCIALFIRMA',
		'RFCFIRMA',
		'NCERTIFICADOFIRMA',
		'FECHAFIRMA',
		'HORAFIRMA',
		'LUGARFIRMA',
		'CADENAFIRMANDA',
		'FIRMAELECTRONICA',
		'PDF',
		'XML',
		'STATUS',
	];
}
