<?php

namespace App\Models;

use CodeIgniter\Model;

class FolioModel extends Model
{

	protected $table            = 'FOLIO';
	protected $allowedFields    = [
		'FOLIOID',
		'ANO',
		'EXPEDIENTEID',
		'DENUNCIANTEID',
		'AGENTEATENCIONID',
		'AGENTEASIGNADOID',
		'OFICINAASIGNADOID',
		'AREAASIGNADOID',
		'MUNICIPIOASIGNADOID',
		'AGENTEFIRMAID',
		'STATUS',
		'NOTASAGENTE',
		'TIPOEXPEDIENTEID',
		'TIPODENUNCIA',
		'ESTADOID',
		'MUNICIPIOID',
		'HECHODELITO',
		'HECHOMEDIOCONOCIMIENTOID',
		'HECHOFECHA',
		'HECHOHORA',
		'HECHOLUGARID',
		'HECHOESTADOID',
		'HECHOMUNICIPIOID',
		'HECHOLOCALIDADID',
		'HECHODELEGACIONID',
		'HECHOZONA',
		'HECHOCOLONIAID',
		'HECHOCOLONIADESCR',
		'HECHOCALLE',
		'HECHONUMEROCASA',
		'HECHONUMEROCASAINT',
		'HECHOREFERENCIA',
		'HECHONARRACION',
		'HECHOCOORDENADAX',
		'HECHOCOORDENADAY',
		'HECHOCLASIFICACIONLUGARID',
		'HECHOVIALIDADID',
		'LOCALIZACIONPERSONA',
		'LOCALIZACIONPERSONAMEDIOS',
		'DERECHOSOFENDIDO',
		'FECHASALIDA',
		'INSTITUCIONREMISIONMUNICIPIOID',
		'INSTITUCIONREMISIONID',
		'NOTIFICACIONES'
	];

	public function get_victimas($folio, $year)
	{
		$strQuery = 'SELECT 
		t1.FOLIOID, t1.ANO, 
		t2.NOMBRE, t2.PRIMERAPELLIDO, t2.SEGUNDOAPELLIDO, t2.PERSONAFISICAID,
		NULL AS PERSONAMORALID, NULL AS DENOMINACION,
		PFCJ.PERSONACALIDADJURIDICADESCR AS PFCJDESCR, NULL AS PMCJDESCR
	  FROM
		FOLIO t1
		LEFT JOIN FOLIOPERSONAFISICA t2 ON t1.FOLIOID = t2.FOLIOID AND t1.ANO = t2.ANO AND (t2.CALIDADJURIDICAID = 1 OR t2.CALIDADJURIDICAID = 6 OR t2.CALIDADJURIDICAID = 3) 
		LEFT JOIN PERSONACALIDADJURIDICA AS PFCJ ON PFCJ.PERSONACALIDADJURIDICAID = t2.CALIDADJURIDICAID
	  WHERE
		t1.FOLIOID = ' . $folio . ' AND t1.ANO = ' . $year . ' AND t2.PERSONAFISICAID IS NOT NULL 
	UNION 
	SELECT 
		t1.FOLIOID, t1.ANO, 
		NULL AS NOMBRE, NULL AS PRIMERAPELLIDO, NULL AS SEGUNDOAPELLIDO, NULL AS PERSONAFISICAID,
		t3.PERSONAMORALID, t3.DENOMINACION,
		NULL AS PFCJDESCR, PMCJ.PERSONACALIDADJURIDICADESCR AS PMCJDESCR
	  FROM
		FOLIO t1
		LEFT JOIN FOLIOPERSONAMORAL t3 ON t1.FOLIOID = t3.FOLIOID AND t1.ANO = t3.ANO AND t3.CALIDADJURIDICAID = 1
		LEFT JOIN PERSONACALIDADJURIDICA AS PMCJ ON PMCJ.PERSONACALIDADJURIDICAID = t3.CALIDADJURIDICAID
	  WHERE 		
		t1.FOLIOID = ' . $folio . ' AND t1.ANO = ' . $year. ' AND t3.PERSONAMORALID IS NOT NULL ';
		return $this->db->query($strQuery)->getResult('array');
		// $query = $builder->get();
		// return $query->getResult('array');
	}

	public function filterDates($obj)
	{
		$strQuery = 'SELECT
		FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.TIPODENUNCIA, FOLIO.FECHAREGISTRO,FOLIO.FECHASALIDA,
		CONCAT(DENUNCIANTES.NOMBRE," ",DENUNCIANTES.APELLIDO_PATERNO," ",DENUNCIANTES.APELLIDO_MATERNO) AS "NOMBRE_DENUNCIANTE", DENUNCIANTES.SEXO AS GENERO,
		CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE", 
		ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,MUNICIPIOHECHO.MUNICIPIODESCR AS MUNICIPIOHECHO,MUNICIPIOASIGNADO.MUNICIPIODESCR AS MUNICIPIOASIGNADO, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR, EMPLEADOS.AREADESCR, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, DELMOD.DELITOMODALIDADDESCR AS DELITO
		FROM FOLIO 
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
		LEFT JOIN MUNICIPIO AS MUNICIPIOASIGNADO ON MUNICIPIOASIGNADO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIOASIGNADO.ESTADOID = 2
		LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID
		LEFT JOIN EMPLEADOS ON EMPLEADOS.EMPLEADOID = FOLIO.AGENTEASIGNADOID AND EMPLEADOS.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN MUNICIPIO as MUNICIPIOHECHO ON MUNICIPIOHECHO.MUNICIPIOID = FOLIO.HECHOMUNICIPIOID AND MUNICIPIOHECHO.ESTADOID = FOLIO.ESTADOID

		LEFT JOIN FOLIOPERSONAFISIMPDELITO ON FOLIO.FOLIOID = FOLIOPERSONAFISIMPDELITO.FOLIOID AND FOLIO.ANO = FOLIOPERSONAFISIMPDELITO.ANO
		LEFT JOIN DELITOMODALIDAD AS DELMOD ON DELMOD.DELITOMODALIDADID = FOLIOPERSONAFISIMPDELITO.DELITOMODALIDADID';

		$fechaInicio = isset($obj['fechaInicio']) ? $obj['fechaInicio'] : '';
		$fechaFin = isset($obj['fechaFin']) ? $obj['fechaFin'] : '';
		$horaInicio = isset($obj['horaInicio']) ? $obj['horaInicio'] : null;
		$horaFin = isset($obj['horaFin']) ? $obj['horaFin'] : null;

		if (isset($obj['fechaInicio'])) {
			unset($obj['fechaInicio']);
		}
		if (isset($obj['fechaFin'])) {
			unset($obj['fechaFin']);
		}
		if (isset($obj['horaInicio'])) {
			unset($obj['horaInicio']);
		}
		if (isset($obj['horaFin'])) {
			unset($obj['horaFin']);
		}

		$count = count($obj);

		if ($count > 0) {
			$strQuery = $strQuery . ' WHERE ';
		}

		foreach ($obj as $clave => $valor) {
			$count -= 1;
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin' && $clave != 'GENERO' && $clave != 'TIPOEXP') {
				$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
			if ($clave == 'GENERO') {
				$strQuery = $strQuery . 'DENUNCIANTES.SEXO' . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
			if ($clave == 'TIPOEXP') {
				$strQuery = $strQuery . 'TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
		}

		if (count($obj) > 0) {
			$strQuery = $strQuery . ' AND ';
		} else {
			$strQuery = $strQuery . ' WHERE ';
		}

		$strQuery = $strQuery . 'FOLIO.FECHASALIDA BETWEEN CAST("' .
			(isset($fechaInicio) ? date("Y-m-d", strtotime($fechaInicio)) : date("Y-m-d")) . ' ' .
			(isset($horaInicio) ? (date('H:i:s', strtotime($horaInicio))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($fechaFin) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($fechaFin)) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($fechaFin))))) : date("Y-m-d")) . ' ' .
			(isset($horaFin) ? (date('H:i:s', strtotime($horaFin))) : '23:59:59') . '" AS DATETIME)';
		$strQuery = $strQuery . 'AND TIPODENUNCIA != "DA"';

		$strQuery = $strQuery . ' GROUP BY FOLIO.FOLIOID, FOLIO.ANO';
		$strQuery = $strQuery . ' ORDER BY FOLIO.FECHASALIDA ASC';
		// var_dump($strQuery);
		// exit;
		$resultAll = $this->db->query($strQuery)->getResult();

		$strQueryCriterio = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC = "CRITERIO DE OPORTUNIDAD"';
		$resultCriterio = $this->db->query($strQueryCriterio)->getResult();

		$strQueryFacultad = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC = "FACULTAD DE ABSTENERSE DE INVESTIGAR (NO DELITO)"';
		$resultFalcultad = $this->db->query($strQueryFacultad)->getResult();

		$strQueryPericiales = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC LIKE "%SOLICITUD DE PERITAJE%"';
		$resultPericiales = $this->db->query($strQueryPericiales)->getResult();

		$arrayCriterio = [];
		foreach ($resultCriterio as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayCriterio, $docto->FOLIOID);
		}
		$arrayFacultad = [];
		foreach ($resultFalcultad as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayFacultad, $docto->FOLIOID);
		}
		$arrayPerciales = [];
		foreach ($resultPericiales as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayPerciales, $docto->FOLIOID);
		}

		foreach ($resultAll as $folio) {

			if (in_array($folio->FOLIOID, $arrayCriterio)) {
				$folio->TIPOEXPEDIENTECLAVE = $folio->TIPOEXPEDIENTECLAVE . ' - CRITERIO';
			};
			if (in_array($folio->FOLIOID, $arrayFacultad)) {
				$folio->TIPOEXPEDIENTECLAVE = $folio->TIPOEXPEDIENTECLAVE . ' - FACULTAD';
			}
			if (in_array($folio->FOLIOID, $arrayPerciales)) {
				$folio->PERICIALES = 'SI';
			}
		}
		$dataView = (object)array();
		$dataView->result = $resultAll;
		// $dataView->strQuery = $strQuery;
		return $dataView;
	}

	public function filterDatesAnonima($obj)
	{
		$strQuery = 'SELECT
		FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.TIPODENUNCIA, FOLIO.FECHAREGISTRO,FOLIO.FECHASALIDA,
		CONCAT(DENUNCIANTES.NOMBRE," ",DENUNCIANTES.APELLIDO_PATERNO," ",DENUNCIANTES.APELLIDO_MATERNO) AS "NOMBRE_DENUNCIANTE", DENUNCIANTES.SEXO AS GENERO,
		CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE", 
		ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,MUNICIPIOASIGNADO.MUNICIPIODESCR AS MUNICIPIOASIGNADO, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR, EMPLEADOS.AREADESCR, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, DELMOD.DELITOMODALIDADDESCR AS DELITO
		FROM FOLIO 
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
		LEFT JOIN MUNICIPIO AS MUNICIPIOASIGNADO ON MUNICIPIOASIGNADO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIOASIGNADO.ESTADOID = 2
		LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID
		LEFT JOIN EMPLEADOS ON EMPLEADOS.EMPLEADOID = FOLIO.AGENTEASIGNADOID AND EMPLEADOS.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN FOLIOPERSONAFISIMPDELITO ON FOLIO.FOLIOID = FOLIOPERSONAFISIMPDELITO.FOLIOID AND FOLIO.ANO = FOLIOPERSONAFISIMPDELITO.ANO
		LEFT JOIN DELITOMODALIDAD AS DELMOD ON DELMOD.DELITOMODALIDADID = FOLIOPERSONAFISIMPDELITO.DELITOMODALIDADID';

		$fechaInicio = isset($obj['fechaInicio']) ? $obj['fechaInicio'] : '';
		$fechaFin = isset($obj['fechaFin']) ? $obj['fechaFin'] : '';
		$horaInicio = isset($obj['horaInicio']) ? $obj['horaInicio'] : null;
		$horaFin = isset($obj['horaFin']) ? $obj['horaFin'] : null;

		if (isset($obj['fechaInicio'])) {
			unset($obj['fechaInicio']);
		}
		if (isset($obj['fechaFin'])) {
			unset($obj['fechaFin']);
		}
		if (isset($obj['horaInicio'])) {
			unset($obj['horaInicio']);
		}
		if (isset($obj['horaFin'])) {
			unset($obj['horaFin']);
		}

		$count = count($obj);

		if ($count > 0) {
			$strQuery = $strQuery . ' WHERE ';
		}

		foreach ($obj as $clave => $valor) {
			$count -= 1;
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin' && $clave != 'GENERO' && $clave != 'TIPOEXP') {
				$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
			if ($clave == 'GENERO') {
				$strQuery = $strQuery . 'DENUNCIANTES.SEXO' . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
			if ($clave == 'TIPOEXP') {
				$strQuery = $strQuery . 'TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
		}

		if (count($obj) > 0) {
			$strQuery = $strQuery . ' AND ';
		} else {
			$strQuery = $strQuery . ' WHERE ';
		}

		$strQuery = $strQuery . 'FOLIO.FECHASALIDA BETWEEN CAST("' .
			(isset($fechaInicio) ? date("Y-m-d", strtotime($fechaInicio)) : date("Y-m-d")) . ' ' .
			(isset($horaInicio) ? (date('H:i:s', strtotime($horaInicio))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($fechaFin) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($fechaFin)) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($fechaFin))))) : date("Y-m-d")) . ' ' .
			(isset($horaFin) ? (date('H:i:s', strtotime($horaFin))) : '23:59:59') . '" AS DATETIME)';

		$strQuery = $strQuery . ' GROUP BY FOLIO.FOLIOID, FOLIO.ANO';
		$strQuery = $strQuery . ' ORDER BY FOLIO.FECHASALIDA ASC';
		// var_dump($strQuery);
		// exit;
		$resultAll = $this->db->query($strQuery)->getResult();

		$strQueryCriterio = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC = "CRITERIO DE OPORTUNIDAD"';
		$resultCriterio = $this->db->query($strQueryCriterio)->getResult();

		$strQueryFacultad = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC = "FACULTAD DE ABSTENERSE DE INVESTIGAR (NO DELITO)"';
		$resultFalcultad = $this->db->query($strQueryFacultad)->getResult();

		$strQueryPericiales = 'SELECT FOLIOID, ANO, NUMEROEXPEDIENTE, FOLIODOCID, TIPODOC FROM FOLIODOC WHERE TIPODOC LIKE "%SOLICITUD DE PERITAJE%"';
		$resultPericiales = $this->db->query($strQueryPericiales)->getResult();

		$arrayCriterio = [];
		foreach ($resultCriterio as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayCriterio, $docto->FOLIOID);
		}
		$arrayFacultad = [];
		foreach ($resultFalcultad as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayFacultad, $docto->FOLIOID);
		}
		$arrayPerciales = [];
		foreach ($resultPericiales as $docto) {
			if ($docto->NUMEROEXPEDIENTE) array_push($arrayPerciales, $docto->FOLIOID);
		}
		foreach ($resultAll as $folio) {

			if (in_array($folio->FOLIOID, $arrayCriterio)) {
				$folio->TIPOEXPEDIENTECLAVE = $folio->TIPOEXPEDIENTECLAVE . ' - CRITERIO';
			};
			if (in_array($folio->FOLIOID, $arrayFacultad)) {
				$folio->TIPOEXPEDIENTECLAVE = $folio->TIPOEXPEDIENTECLAVE . ' - FACULTAD';
			}
			if (in_array($folio->FOLIOID, $arrayPerciales)) {
				$folio->PERCICIALES = 'SI';
			}
		}

		$dataView = (object)array();
		$dataView->result = $resultAll;
		// $dataView->strQuery = $strQuery;
		return $dataView;
	}

	public function filterAllDates($obj)
	{
		$strQuery = 'SELECT FOLIO.*, ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,
		CONCAT(DENUNCIANTES.NOMBRE," ",DENUNCIANTES.APELLIDO_PATERNO," ",DENUNCIANTES.APELLIDO_MATERNO) AS "NOMBRE_DENUNCIANTE",
		CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE", 
		MUNICIPIOASIGNADO.MUNICIPIODESCR AS MUNICIPIOASIGNADO, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE,OFICINA.OFICINADESCR,
		GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
		BANDEJARAC.MODULODESCR
		FROM FOLIO
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
		LEFT JOIN MUNICIPIO AS MUNICIPIOASIGNADO ON MUNICIPIOASIGNADO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIOASIGNADO.ESTADOID = 2
		LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID
		LEFT JOIN EMPLEADOS ON EMPLEADOS.EMPLEADOID = FOLIO.AGENTEASIGNADOID AND EMPLEADOS.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
		LEFT JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID
		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN BANDEJARAC ON BANDEJARAC.FOLIOID = FOLIO.FOLIOID AND BANDEJARAC.ANO = FOLIO.ANO
';

		$fechaInicio = isset($obj['fechaInicio']) ? $obj['fechaInicio'] : '';
		$fechaFin = isset($obj['fechaFin']) ? $obj['fechaFin'] : '';
		$horaInicio = isset($obj['horaInicio']) ? $obj['horaInicio'] : null;
		$horaFin = isset($obj['horaFin']) ? $obj['horaFin'] : null;

		if (isset($obj['fechaInicio'])) {
			unset($obj['fechaInicio']);
		}
		if (isset($obj['fechaFin'])) {
			unset($obj['fechaFin']);
		}
		if (isset($obj['horaInicio'])) {
			unset($obj['horaInicio']);
		}
		if (isset($obj['horaFin'])) {
			unset($obj['horaFin']);
		}

		$count = count($obj);

		if ($count > 0) {
			$strQuery = $strQuery . ' WHERE ';
		}

		foreach ($obj as $clave => $valor) {
			$count -= 1;
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin') {
				$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
		}

		if (count($obj) > 0) {
			$strQuery = $strQuery . ' AND ';
		} else {
			$strQuery = $strQuery . ' WHERE ';
		}


		$strQuery =
			$strQuery . 'FOLIO.FECHAREGISTRO BETWEEN CAST("' .
			(isset($fechaInicio) ? date("Y-m-d", strtotime($fechaInicio)) : date("Y-m-d")) . ' ' .
			(isset($horaInicio) ? (date('H:i:s', strtotime($horaInicio))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($fechaFin) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($fechaFin)) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($fechaFin))))) : date("Y-m-d")) . ' ' .
			(isset($horaFin) ? (date('H:i:s', strtotime($horaFin))) : '23:59:59') . '" AS DATETIME)';

		$strQuery = $strQuery . 'AND TIPODENUNCIA != "ES"';
		$strQuery = $strQuery . 'GROUP BY FOLIO.FOLIOID, FOLIO.ANO';
		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;
		// $dataView->strQuery = $strQuery;
		return $dataView;
	}

	public function filterAllDatesLitigante($obj)
	{
		$strQuery = 'SELECT FOLIO.*, ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,
		CONCAT(DENUNCIANTES.NOMBRE," ",DENUNCIANTES.APELLIDO_PATERNO," ",DENUNCIANTES.APELLIDO_MATERNO) AS "NOMBRE_DENUNCIANTE",
		CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE", 
		MUNICIPIOASIGNADO.MUNICIPIODESCR AS MUNICIPIOASIGNADO, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE,EMPLEADOS.OFICINADESCR,
		GROUP_CONCAT(DELITOMODALIDAD_FIS.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR_FIS",
    	GROUP_CONCAT(DELITOMODALIDAD_MORAL.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR_MORAL",		
		BANDEJARAC.MODULODESCR
		FROM FOLIO
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
		LEFT JOIN MUNICIPIO AS MUNICIPIOASIGNADO ON MUNICIPIOASIGNADO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIOASIGNADO.ESTADOID = 2
		LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID
		LEFT JOIN EMPLEADOS ON EMPLEADOS.EMPLEADOID = FOLIO.AGENTEASIGNADOID AND EMPLEADOS.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
		LEFT JOIN FOLIORELACIONMORALFIS ON FOLIORELACIONMORALFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONMORALFIS.ANO = FOLIO.ANO 
		LEFT JOIN DELITOMODALIDAD AS DELITOMODALIDAD_FIS  ON DELITOMODALIDAD_FIS.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID
		LEFT JOIN DELITOMODALIDAD AS DELITOMODALIDAD_MORAL ON DELITOMODALIDAD_MORAL.DELITOMODALIDADID = FOLIORELACIONMORALFIS.DELITOMODALIDADID

		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN BANDEJARAC ON BANDEJARAC.FOLIOID = FOLIO.FOLIOID AND BANDEJARAC.ANO = FOLIO.ANO
';

		$fechaInicio = isset($obj['fechaInicio']) ? $obj['fechaInicio'] : '';
		$fechaFin = isset($obj['fechaFin']) ? $obj['fechaFin'] : '';
		$horaInicio = isset($obj['horaInicio']) ? $obj['horaInicio'] : null;
		$horaFin = isset($obj['horaFin']) ? $obj['horaFin'] : null;

		if (isset($obj['fechaInicio'])) {
			unset($obj['fechaInicio']);
		}
		if (isset($obj['fechaFin'])) {
			unset($obj['fechaFin']);
		}
		if (isset($obj['horaInicio'])) {
			unset($obj['horaInicio']);
		}
		if (isset($obj['horaFin'])) {
			unset($obj['horaFin']);
		}

		$count = count($obj);

		if ($count > 0) {
			$strQuery = $strQuery . ' WHERE ';
		}

		foreach ($obj as $clave => $valor) {
			$count -= 1;
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin') {
				$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
		}

		if (count($obj) > 0) {
			$strQuery = $strQuery . ' AND ';
		} else {
			$strQuery = $strQuery . ' WHERE ';
		}


		$strQuery =
			$strQuery . 'FOLIO.FECHAREGISTRO BETWEEN CAST("' .
			(isset($fechaInicio) ? date("Y-m-d", strtotime($fechaInicio)) : date("Y-m-d")) . ' ' .
			(isset($horaInicio) ? (date('H:i:s', strtotime($horaInicio))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($fechaFin) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($fechaFin)) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($fechaFin))))) : date("Y-m-d")) . ' ' .
			(isset($horaFin) ? (date('H:i:s', strtotime($horaFin))) : '23:59:59') . '" AS DATETIME)';

		$strQuery = $strQuery . ' AND FOLIO.TIPODENUNCIA = "ES"';
		$strQuery = $strQuery . ' GROUP BY FOLIO.FOLIOID';
		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;
		// $dataView->strQuery = $strQuery;
		return $dataView;
	}

	public function bandeja_salida($municipio)
	{
		$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO, FOLIO.AGENTEATENCIONID, FOLIO.EXPEDIENTEID, FOLIO.MUNICIPIOASIGNADOID, FOLIO.STATUS, FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, FOLIO.HECHODELITO, FOLIO.NOTASAGENTE, FOLIO.HECHOCALLE,FOLIO.HECHONUMEROCASA,FOLIO.HECHOCOLONIADESCR,FOLIO.HECHONUMEROCASAINT,ESTADO.ESTADODESCR, MUNICIPIO.MUNICIPIODESCR, MUNICIPIO.MUNICIPIOID, FOLIO.TIPODENUNCIA,
		TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE",
		GROUP_CONCAT(DISTINCT DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",GROUP_CONCAT(FOLIODOC.STATUS) AS "STATUSDOCUMENTO"
		FROM FOLIO 
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
		LEFT JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID
		LEFT JOIN BANDEJARAC ON BANDEJARAC.EXPEDIENTEID = FOLIO.EXPEDIENTEID
		LEFT JOIN FOLIODOC ON FOLIODOC.FOLIOID = FOLIO.FOLIOID AND FOLIODOC.ANO = FOLIO.ANO
		WHERE FOLIO.MUNICIPIOASIGNADOID = ' . $municipio . ' AND FOLIO.EXPEDIENTEID IS NOT NULL AND FOLIO.AGENTEASIGNADOID IS NULL AND BANDEJARAC.EXPEDIENTEID IS NULL
		GROUP BY EXPEDIENTEID;';

		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;
		return $dataView;
	}


	public function countFolioDenunciante($denuncianteid)
	{
		$strQuery = 'SELECT COUNT(*) AS "folios_pendientes" FROM FOLIO WHERE DENUNCIANTEID = ' . $denuncianteid . ' AND (STATUS = "ABIERTO" OR STATUS = "EN PROCESO")';
		$result = $this->db->query($strQuery)->getRow();

		return $result;
	}

	public function videos_expediente_model($tipo)
	{
		if ($tipo == 1) {
			$strQuery = '
			SELECT FOLIO.FOLIOID,FOLIO.ANO,FOLIO.EXPEDIENTEID, ROLES.NOMBRE_ROL, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,
			CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",APELLIDO_MATERNO) as NOMBREAGENTE,
			GROUP_CONCAT(DISTINCT IMPUTADO.NOMBRE," ",IF(IMPUTADO.PRIMERAPELLIDO IS NOT NULL, IMPUTADO.PRIMERAPELLIDO, "")," ",IF(IMPUTADO.SEGUNDOAPELLIDO IS NOT NULL, IMPUTADO.SEGUNDOAPELLIDO, "")," ") AS IMPUTADOS,
			GROUP_CONCAT(DISTINCT OFENDIDO.NOMBRE," ",IF(OFENDIDO.PRIMERAPELLIDO IS NOT NULL, OFENDIDO.PRIMERAPELLIDO, "")," ",IF(OFENDIDO.SEGUNDOAPELLIDO IS NOT NULL, OFENDIDO.SEGUNDOAPELLIDO, "")," ") AS OFENDIDOS,
			GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			MUNICIPIO.MUNICIPIODESCR AS MUNICIPIO
			FROM FOLIO
            LEFT JOIN MUNICIPIO ON FOLIO.MUNICIPIOASIGNADOID = MUNICIPIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = 2
			LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
			LEFT JOIN ROLES ON ROLES.ID = USUARIOS.ROLID 
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
			LEFT JOIN FOLIOPERSONAFISICA AS IMPUTADO ON IMPUTADO.FOLIOID = FOLIO.FOLIOID  AND IMPUTADO.ANO = FOLIO.ANO AND IMPUTADO.CALIDADJURIDICAID = 2
			LEFT JOIN FOLIOPERSONAFISICA AS OFENDIDO ON OFENDIDO.FOLIOID = FOLIO.FOLIOID AND  OFENDIDO.ANO = FOLIO.ANO
			INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			WHERE EXPEDIENTEID IS NOT NULL 
			AND AGENTEATENCIONID IS NOT NULL 
			AND FOLIO.TIPOEXPEDIENTEID IS NOT NULL
			AND ( OFENDIDO.CALIDADJURIDICAID = 1 OR  OFENDIDO.CALIDADJURIDICAID = 6)
			GROUP BY FOLIO.FOLIOID,FOLIO.ANO
			;';
		} else if ($tipo == 2) {
			$strQuery = '
			SELECT FOLIO.FOLIOID,FOLIO.ANO,FOLIO.EXPEDIENTEID, ROLES.NOMBRE_ROL, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,
			CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",APELLIDO_MATERNO) as NOMBREAGENTE,
			GROUP_CONCAT(DISTINCT IMPUTADO.NOMBRE," ",IF(IMPUTADO.PRIMERAPELLIDO IS NOT NULL, IMPUTADO.PRIMERAPELLIDO, "")," ",IF(IMPUTADO.SEGUNDOAPELLIDO IS NOT NULL, IMPUTADO.SEGUNDOAPELLIDO, "")," ") AS IMPUTADOS,
			GROUP_CONCAT(DISTINCT OFENDIDO.NOMBRE," ",IF(OFENDIDO.PRIMERAPELLIDO IS NOT NULL, OFENDIDO.PRIMERAPELLIDO, "")," ",IF(OFENDIDO.SEGUNDOAPELLIDO IS NOT NULL, OFENDIDO.SEGUNDOAPELLIDO, "")," ") AS OFENDIDOS,
			GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			MUNICIPIO.MUNICIPIODESCR AS MUNICIPIO
			FROM FOLIO
            LEFT JOIN MUNICIPIO ON FOLIO.MUNICIPIOASIGNADOID = MUNICIPIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = 2
			LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
			LEFT JOIN ROLES ON ROLES.ID = USUARIOS.ROLID 
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
			LEFT JOIN FOLIOPERSONAFISICA AS IMPUTADO ON IMPUTADO.FOLIOID = FOLIO.FOLIOID  AND IMPUTADO.ANO = FOLIO.ANO AND IMPUTADO.CALIDADJURIDICAID = 2
			LEFT JOIN FOLIOPERSONAFISICA AS OFENDIDO ON OFENDIDO.FOLIOID = FOLIO.FOLIOID AND  OFENDIDO.ANO = FOLIO.ANO
			INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			WHERE EXPEDIENTEID IS NOT NULL 
			AND AGENTEATENCIONID IS NOT NULL 
			AND FOLIO.TIPOEXPEDIENTEID IS NOT NULL
			AND ( OFENDIDO.CALIDADJURIDICAID = 1 OR  OFENDIDO.CALIDADJURIDICAID = 6)
			AND FOLIO.MUNICIPIOASIGNADOID =' . session('MUNICIPIOID') . '
			AND FOLIO.OFICINAASIGNADOID = ' . session('OFICINAID') . '
			GROUP BY FOLIO.FOLIOID,FOLIO.ANO
			;';
		} else if ($tipo == 3) {
			$strQuery = '
			SELECT FOLIO.FOLIOID,FOLIO.ANO,FOLIO.EXPEDIENTEID, ROLES.NOMBRE_ROL, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,
			CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",APELLIDO_MATERNO) as NOMBREAGENTE,
			GROUP_CONCAT(DISTINCT IMPUTADO.NOMBRE," ",IF(IMPUTADO.PRIMERAPELLIDO IS NOT NULL, IMPUTADO.PRIMERAPELLIDO, "")," ",IF(IMPUTADO.SEGUNDOAPELLIDO IS NOT NULL, IMPUTADO.SEGUNDOAPELLIDO, "")," ") AS IMPUTADOS,
			GROUP_CONCAT(DISTINCT OFENDIDO.NOMBRE," ",IF(OFENDIDO.PRIMERAPELLIDO IS NOT NULL, OFENDIDO.PRIMERAPELLIDO, "")," ",IF(OFENDIDO.SEGUNDOAPELLIDO IS NOT NULL, OFENDIDO.SEGUNDOAPELLIDO, "")," ") AS OFENDIDOS,
			GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			MUNICIPIO.MUNICIPIODESCR AS MUNICIPIO
			FROM FOLIO
            LEFT JOIN MUNICIPIO ON FOLIO.MUNICIPIOASIGNADOID = MUNICIPIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = 2
			LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
			LEFT JOIN ROLES ON ROLES.ID = USUARIOS.ROLID 
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
			LEFT JOIN FOLIOPERSONAFISICA AS IMPUTADO ON IMPUTADO.FOLIOID = FOLIO.FOLIOID  AND IMPUTADO.ANO = FOLIO.ANO AND IMPUTADO.CALIDADJURIDICAID = 2
			LEFT JOIN FOLIOPERSONAFISICA AS OFENDIDO ON OFENDIDO.FOLIOID = FOLIO.FOLIOID AND  OFENDIDO.ANO = FOLIO.ANO
			INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			WHERE EXPEDIENTEID IS NOT NULL 
			AND AGENTEATENCIONID IS NOT NULL 
			AND FOLIO.TIPOEXPEDIENTEID IS NOT NULL
			AND ( OFENDIDO.CALIDADJURIDICAID = 1 OR  OFENDIDO.CALIDADJURIDICAID = 6)
			AND FOLIO.MUNICIPIOASIGNADOID = ' . session('MUNICIPIOID') . ' AND FOLIO.TIPOEXPEDIENTEID = 5 GROUP BY FOLIO.FOLIOID, FOLIO.ANO;';
		} else if ($tipo == 4) {
			$strQuery = '
			SELECT FOLIO.FOLIOID,FOLIO.ANO,FOLIO.EXPEDIENTEID, ROLES.NOMBRE_ROL, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,
			CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",APELLIDO_MATERNO) as NOMBREAGENTE,
			GROUP_CONCAT(DISTINCT IMPUTADO.NOMBRE," ",IF(IMPUTADO.PRIMERAPELLIDO IS NOT NULL, IMPUTADO.PRIMERAPELLIDO, "")," ",IF(IMPUTADO.SEGUNDOAPELLIDO IS NOT NULL, IMPUTADO.SEGUNDOAPELLIDO, "")," ") AS IMPUTADOS,
			GROUP_CONCAT(DISTINCT OFENDIDO.NOMBRE," ",IF(OFENDIDO.PRIMERAPELLIDO IS NOT NULL, OFENDIDO.PRIMERAPELLIDO, "")," ",IF(OFENDIDO.SEGUNDOAPELLIDO IS NOT NULL, OFENDIDO.SEGUNDOAPELLIDO, "")," ") AS OFENDIDOS,
			GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			MUNICIPIO.MUNICIPIODESCR AS MUNICIPIO
			FROM FOLIO
            LEFT JOIN MUNICIPIO ON FOLIO.MUNICIPIOASIGNADOID = MUNICIPIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = 2
			LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
			LEFT JOIN ROLES ON ROLES.ID = USUARIOS.ROLID 
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
			LEFT JOIN FOLIOPERSONAFISICA AS IMPUTADO ON IMPUTADO.FOLIOID = FOLIO.FOLIOID  AND IMPUTADO.ANO = FOLIO.ANO AND IMPUTADO.CALIDADJURIDICAID = 2
			LEFT JOIN FOLIOPERSONAFISICA AS OFENDIDO ON OFENDIDO.FOLIOID = FOLIO.FOLIOID AND  OFENDIDO.ANO = FOLIO.ANO
			INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			WHERE EXPEDIENTEID IS NOT NULL 
			AND AGENTEATENCIONID = ' . session('ID') . ' 
			AND FOLIO.TIPOEXPEDIENTEID IS NOT NULL
			AND ( OFENDIDO.CALIDADJURIDICAID = 1 OR  OFENDIDO.CALIDADJURIDICAID = 6)
			GROUP BY FOLIO.FOLIOID,FOLIO.ANO
			;';
		} else if ($tipo == 5) {
			$municipiosoficinas = json_decode(session('MUNICIPIOSOFICINASID'));
			$municipios = [];
			$oficinas = [];

			foreach ($municipiosoficinas as $item) {
				$municipios[] = $item->MUNICIPIOID;
				$oficinas[] = $item->OFICINAID;
			}

			$strQuery = '
			SELECT FOLIO.FOLIOID,FOLIO.ANO,FOLIO.EXPEDIENTEID, ROLES.NOMBRE_ROL, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,
			CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",APELLIDO_MATERNO) as NOMBREAGENTE,
			GROUP_CONCAT(DISTINCT IMPUTADO.NOMBRE," ",IF(IMPUTADO.PRIMERAPELLIDO IS NOT NULL, IMPUTADO.PRIMERAPELLIDO, "")," ",IF(IMPUTADO.SEGUNDOAPELLIDO IS NOT NULL, IMPUTADO.SEGUNDOAPELLIDO, "")," ") AS IMPUTADOS,
			GROUP_CONCAT(DISTINCT OFENDIDO.NOMBRE," ",IF(OFENDIDO.PRIMERAPELLIDO IS NOT NULL, OFENDIDO.PRIMERAPELLIDO, "")," ",IF(OFENDIDO.SEGUNDOAPELLIDO IS NOT NULL, OFENDIDO.SEGUNDOAPELLIDO, "")," ") AS OFENDIDOS,
			GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			MUNICIPIO.MUNICIPIODESCR AS MUNICIPIO
			FROM FOLIO
            LEFT JOIN MUNICIPIO ON FOLIO.MUNICIPIOASIGNADOID = MUNICIPIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = 2
			LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID 
			LEFT JOIN ROLES ON ROLES.ID = USUARIOS.ROLID 
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID 
			LEFT JOIN FOLIOPERSONAFISICA AS IMPUTADO ON IMPUTADO.FOLIOID = FOLIO.FOLIOID  AND IMPUTADO.ANO = FOLIO.ANO AND IMPUTADO.CALIDADJURIDICAID = 2
			LEFT JOIN FOLIOPERSONAFISICA AS OFENDIDO ON OFENDIDO.FOLIOID = FOLIO.FOLIOID AND  OFENDIDO.ANO = FOLIO.ANO
			INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			WHERE EXPEDIENTEID IS NOT NULL 
			AND AGENTEATENCIONID IS NOT NULL 
			AND FOLIO.TIPOEXPEDIENTEID IS NOT NULL
			AND ( OFENDIDO.CALIDADJURIDICAID = 1 OR  OFENDIDO.CALIDADJURIDICAID = 6)
			AND FOLIO.MUNICIPIOASIGNADOID IN (' . implode(',', $municipios) . ')
			AND FOLIO.OFICINAASIGNADOID IN (' . implode(',', $oficinas) . ')
			GROUP BY FOLIO.FOLIOID, FOLIO.ANO
			;';
		}
		$result = $this->db->query($strQuery)->getResult();
		return $result;
	}

	public function filterDatesRegistroDiario($obj)
	{
		if (isset($obj['STATUS'])) {
			if ($obj['STATUS'] == "CON") {

				$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO,FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, FOLIO.HECHODELITO, FOLIO.NOTASAGENTE,FOLIO.TIPOEXPEDIENTEID,
				DENUNCIANTES.NOMBRE AS "N_DENUNCIANTE", DENUNCIANTES.APELLIDO_PATERNO AS "APP_DENUNCIANTE", DENUNCIANTES.APELLIDO_MATERNO AS "APM_DENUNCIANTE",DENUNCIANTES.TELEFONO AS "TELEFONODENUNCIANTE",DENUNCIANTES.CORREO AS "CORREODENUNCIANTE",  DENUNCIANTES.SEXO AS "GENERO",
				USUARIOS.NOMBRE AS "N_AGENT", USUARIOS.APELLIDO_PATERNO AS "APP_AGENT", USUARIOS.APELLIDO_MATERNO AS "APM_AGENT",
				ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR,FOLIO.TIPODENUNCIA,  GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
				BANDEJARAC.MODULODESCR AS "REMISION_RAC",
				DERIVACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_DERIVACION",
				CANALIZACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_CANALIZACION",
				OFICINA.OFICINADESCR AS "OFICINA_EMP",
				CONCAT(FOLIO.FOLIOID, "/", FOLIO.ANO) AS FOLIOFULL
				FROM FOLIO 
				INNER JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
				INNER JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
				INNER JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
				INNER JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO. TIPOEXPEDIENTEID
				INNER JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
				INNER JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
				INNER JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
				LEFT JOIN BANDEJARAC ON FOLIO.FOLIOID = BANDEJARAC.FOLIOID AND  FOLIO.ANO = BANDEJARAC.ANO
				LEFT JOIN DERIVACIONES ON FOLIO.INSTITUCIONREMISIONID = DERIVACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = DERIVACIONES.MUNICIPIOID
				LEFT JOIN CANALIZACIONES ON FOLIO.INSTITUCIONREMISIONID = CANALIZACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = CANALIZACIONES.MUNICIPIOID
				LEFT JOIN EMPLEADOS ON FOLIO.AGENTEASIGNADOID = EMPLEADOS.EMPLEADOID
				LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID

				WHERE NOT FOLIO.EXPEDIENTEID IS NULL';
				if (!empty($obj['AGENTEATENCIONID'])) $strQuery = $strQuery . ' AND FOLIO.AGENTEATENCIONID = ' . $obj['AGENTEATENCIONID'];
				$strQuery =
					$strQuery . ' AND ' .
					'FOLIO.FECHASALIDA BETWEEN CAST("' .
					(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
					(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
					(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
					(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
				if (isset($obj['GENERO'])) {
					$strQuery = $strQuery . 'AND DENUNCIANTES.SEXO' . ' = ' . '"' . $obj['GENERO'] . '"';
				}
				if (isset($obj['TIPOEXP'])) {
					$strQuery = $strQuery . 'AND TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $obj['TIPOEXP'] . '"';
				}
				if (isset($obj['TIPODENUNCIA'])) {
					$strQuery = $strQuery . 'AND FOLIO.TIPODENUNCIA' . ' = ' . '"' . $obj['TIPODENUNCIA'] . '"';
				}
				$strQuery = $strQuery . ' GROUP BY  FOLIO.FOLIOID, FOLIO.ANO';
			}
			if ($obj['STATUS'] == "SIN") {
				$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, FOLIO.HECHODELITO, FOLIO.NOTASAGENTE,FOLIO.TIPOEXPEDIENTEID,
			DENUNCIANTES.NOMBRE AS "N_DENUNCIANTE", DENUNCIANTES.APELLIDO_PATERNO AS "APP_DENUNCIANTE", DENUNCIANTES.APELLIDO_MATERNO AS "APM_DENUNCIANTE",DENUNCIANTES.TELEFONO AS "TELEFONODENUNCIANTE",DENUNCIANTES.CORREO AS "CORREODENUNCIANTE",  DENUNCIANTES.SEXO AS "GENERO",
				USUARIOS.NOMBRE AS "N_AGENT", USUARIOS.APELLIDO_PATERNO AS "APP_AGENT", USUARIOS.APELLIDO_MATERNO AS "APM_AGENT", 
				ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,FOLIO.TIPODENUNCIA, GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
				BANDEJARAC.MODULODESCR AS "REMISION_RAC",
				DERIVACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_DERIVACION",
				CANALIZACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_CANALIZACION",
				OFICINA.OFICINADESCR AS "OFICINA_EMP",
				CONCAT(FOLIO.FOLIOID, "/", FOLIO.ANO) AS FOLIOFULL

				FROM FOLIO 
				LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
				LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
				LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
				LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
				LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
				LEFT JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
				LEFT JOIN BANDEJARAC ON FOLIO.FOLIOID = BANDEJARAC.FOLIOID AND  FOLIO.ANO = BANDEJARAC.ANO
				LEFT JOIN DERIVACIONES ON FOLIO.INSTITUCIONREMISIONID = DERIVACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = DERIVACIONES.MUNICIPIOID
				LEFT JOIN CANALIZACIONES ON FOLIO.INSTITUCIONREMISIONID = CANALIZACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = CANALIZACIONES.MUNICIPIOID
				LEFT JOIN EMPLEADOS ON FOLIO.AGENTEASIGNADOID = EMPLEADOS.EMPLEADOID
				LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID

				WHERE FOLIO.EXPEDIENTEID IS NULL';
				if (!empty($obj['AGENTEATENCIONID'])) $strQuery = $strQuery . ' AND FOLIO.AGENTEATENCIONID = ' . $obj['AGENTEATENCIONID'];

				$strQuery =
					$strQuery . ' AND ' .
					'FOLIO.FECHASALIDA BETWEEN CAST("' .
					(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
					(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
					(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
					(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
				if (isset($obj['GENERO'])) {
					$strQuery = $strQuery . 'AND DENUNCIANTES.SEXO' . ' = ' . '"' . $obj['GENERO'] . '"';
				}
				if (isset($obj['TIPOEXP'])) {
					$strQuery = $strQuery . 'AND TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $obj['TIPOEXP'] . '"';
				}
				if (isset($obj['TIPODENUNCIA'])) {
					$strQuery = $strQuery . 'AND FOLIO.TIPODENUNCIA' . ' = ' . '"' . $obj['TIPODENUNCIA'] . '"';
				}
				$strQuery = $strQuery . ' GROUP BY  FOLIO.FOLIOID, FOLIO.ANO';
			}
			if ($obj['STATUS'] == "TODOS") {
				$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, FOLIO.HECHODELITO, FOLIO.NOTASAGENTE,FOLIO.TIPOEXPEDIENTEID,
			DENUNCIANTES.NOMBRE AS "N_DENUNCIANTE", DENUNCIANTES.APELLIDO_PATERNO AS "APP_DENUNCIANTE", DENUNCIANTES.APELLIDO_MATERNO AS "APM_DENUNCIANTE",DENUNCIANTES.TELEFONO AS "TELEFONODENUNCIANTE",DENUNCIANTES.CORREO AS "CORREODENUNCIANTE",  DENUNCIANTES.SEXO AS "GENERO",
				USUARIOS.NOMBRE AS "N_AGENT", USUARIOS.APELLIDO_PATERNO AS "APP_AGENT", USUARIOS.APELLIDO_MATERNO AS "APM_AGENT", 
				ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR,FOLIO.TIPODENUNCIA,GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
				BANDEJARAC.MODULODESCR AS "REMISION_RAC",
				DERIVACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_DERIVACION",
				CANALIZACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_CANALIZACION",
				OFICINA.OFICINADESCR AS "OFICINA_EMP",
				CONCAT(FOLIO.FOLIOID, "/", FOLIO.ANO) AS FOLIOFULL

				FROM FOLIO 
				INNER JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
				LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
				INNER JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
				INNER JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
				LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO. TIPOEXPEDIENTEID
				LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
				LEFT JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
				LEFT JOIN BANDEJARAC ON FOLIO.FOLIOID = BANDEJARAC.FOLIOID AND  FOLIO.ANO = BANDEJARAC.ANO
			LEFT JOIN DERIVACIONES ON FOLIO.INSTITUCIONREMISIONID = DERIVACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = DERIVACIONES.MUNICIPIOID
				LEFT JOIN CANALIZACIONES ON FOLIO.INSTITUCIONREMISIONID = CANALIZACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = CANALIZACIONES.MUNICIPIOID
				LEFT JOIN EMPLEADOS ON FOLIO.AGENTEASIGNADOID = EMPLEADOS.EMPLEADOID
				LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
';
				if (isset($obj['AGENTEATENCIONID'])) $strQuery = $strQuery . '	WHERE FOLIO.AGENTEATENCIONID = ' . $obj['AGENTEATENCIONID'];

				// $strQuery= $strQuery . ' AND '.'WHERE FOLIO.AGENTEATENCIONID= ' .$objusuario['agenteatencion'];

				$strQuery =
					$strQuery . ' AND ' .
					'FOLIO.FECHASALIDA BETWEEN CAST("' .
					(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
					(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
					(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
					(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
				if (isset($obj['GENERO'])) {
					$strQuery = $strQuery . 'AND DENUNCIANTES.SEXO' . ' = ' . '"' . $obj['GENERO'] . '"';
				}
				if (isset($obj['TIPOEXP'])) {
					$strQuery = $strQuery . 'AND TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $obj['TIPOEXP'] . '"';
				}
				if (isset($obj['TIPODENUNCIA'])) {
					$strQuery = $strQuery . 'AND FOLIO.TIPODENUNCIA' . ' = ' . '"' . $obj['TIPODENUNCIA'] . '"';
				}
				$strQuery = $strQuery . ' GROUP BY  FOLIO.FOLIOID, FOLIO.ANO';
			}
		} else {
			$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, FOLIO.HECHODELITO, FOLIO.NOTASAGENTE,FOLIO.TIPOEXPEDIENTEID,
			DENUNCIANTES.NOMBRE AS "N_DENUNCIANTE", DENUNCIANTES.APELLIDO_PATERNO AS "APP_DENUNCIANTE", DENUNCIANTES.APELLIDO_MATERNO AS "APM_DENUNCIANTE",DENUNCIANTES.TELEFONO AS "TELEFONODENUNCIANTE",DENUNCIANTES.CORREO AS "CORREODENUNCIANTE",  DENUNCIANTES.SEXO AS "GENERO",
			USUARIOS.NOMBRE AS "N_AGENT", USUARIOS.APELLIDO_PATERNO AS "APP_AGENT", USUARIOS.APELLIDO_MATERNO AS "APM_AGENT", 
			ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR , FOLIO.TIPODENUNCIA,  GROUP_CONCAT(DELITOMODALIDAD.DELITOMODALIDADDESCR) AS "DELITOMODALIDADDESCR",
			BANDEJARAC.MODULODESCR AS "REMISION_RAC",
				DERIVACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_DERIVACION",
				CANALIZACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_CANALIZACION",
				OFICINA.OFICINADESCR AS "OFICINA_EMP",
				CONCAT(FOLIO.FOLIOID, "/", FOLIO.ANO) AS FOLIOFULL

			FROM FOLIO 
			INNER JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
			LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
			LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO. TIPOEXPEDIENTEID
			INNER JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
			INNER JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
			LEFT JOIN FOLIORELACIONFISFIS ON FOLIORELACIONFISFIS.FOLIOID = FOLIO.FOLIOID AND FOLIORELACIONFISFIS.ANO = FOLIO.ANO 
			LEFT JOIN DELITOMODALIDAD ON DELITOMODALIDAD.DELITOMODALIDADID = FOLIORELACIONFISFIS.DELITOMODALIDADID 
			LEFT JOIN BANDEJARAC ON FOLIO.FOLIOID = BANDEJARAC.FOLIOID AND  FOLIO.ANO = BANDEJARAC.ANO
			LEFT JOIN DERIVACIONES ON FOLIO.INSTITUCIONREMISIONID = DERIVACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = DERIVACIONES.MUNICIPIOID
				LEFT JOIN CANALIZACIONES ON FOLIO.INSTITUCIONREMISIONID = CANALIZACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = CANALIZACIONES.MUNICIPIOID
				LEFT JOIN EMPLEADOS ON FOLIO.AGENTEASIGNADOID = EMPLEADOS.EMPLEADOID
				LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
';

			$strQuery =
				$strQuery . ' WHERE ' .
				'FOLIO.FECHASALIDA BETWEEN CAST("' .
				(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
				(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
				(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
				(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
			///if (isset($obj['AGENTEATENCIONID'])) $strQuery = $strQuery . '	AND FOLIO.AGENTEATENCIONID = ' . $obj['AGENTEATENCIONID'];
			foreach ($obj as $clave => $valor) {
				if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin' && $clave != 'GENERO' && $clave != 'TIPOEXP') {
					$strQuery = $strQuery . ' AND ';
					$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';
				}
			}
			if (isset($obj['GENERO'])) {
				$strQuery = $strQuery . 'AND DENUNCIANTES.SEXO' . ' = ' . '"' . $obj['GENERO'] . '"';
			}
			if (isset($obj['TIPOEXP'])) {
				$strQuery = $strQuery . 'AND TIPOEXPEDIENTE.TIPOEXPEDIENTEID' . ' = ' . '"' . $obj['TIPOEXP'] . '"';
			}
			if (isset($obj['TIPODENUNCIA'])) {
				$strQuery = $strQuery . 'AND FOLIO.TIPODENUNCIA' . ' = ' . '"' . $obj['TIPODENUNCIA'] . '"';
			}
			$strQuery = $strQuery . ' GROUP BY  FOLIO.FOLIOID, FOLIO.ANO';
		}
		$strQuery = $strQuery . ' ORDER BY FOLIO.FECHASALIDA DESC';

		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;
		return $dataView;

		// $dataView->strQuery = $strQuery;

	}

	public function filterDatesDocumentos($obj)
	{
		$strQuery = 'SELECT FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.FECHAREGISTRO, FOLIO.FECHASALIDA,FOLIO.STATUS, FOLIO.ANO
			FROM FOLIO ';
		$count = 0;
		foreach ($obj as $clave => $valor) {
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin') {
				if ($count == 0) {
					$strQuery = $strQuery . 'WHERE ';
					$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';
				} else {
					$strQuery = $strQuery . 'AND ';
					$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';
				}
				$count++;
			}
		}
		if ($count == 0) {
			$strQuery =
				$strQuery .
				'WHERE FOLIO.FECHASALIDA BETWEEN CAST("' .
				(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
				(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
				(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
				(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
		}
		$strQuery =
			$strQuery .
			'AND FOLIO.FECHASALIDA BETWEEN CAST("' .
			(isset($obj['fechaInicio']) ? date("Y-m-d", strtotime($obj['fechaInicio'])) : date("Y-m-d")) . ' ' .
			(isset($obj['horaInicio']) ? (date('H:i:s', strtotime($obj['horaInicio']))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($obj['fechaFin']) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($obj['fechaFin'])) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($obj['fechaFin']))))) : date("Y-m-d")) . ' ' .
			(isset($obj['horaFin']) ? (date('H:i:s', strtotime($obj['horaFin']))) : '23:59:59') . '" AS DATETIME)';
		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;

		return $dataView;
	}

	public function get_folio_expediente()
	{
		$builder = $this->db->table($this->table);
		$builder->select(['FOLIOID', 'EXPEDIENTEID', 'FECHAREGISTRO', 'STATUS', 'ANO']);
		$builder->where('STATUS', 'EXPEDIENTE');
		$builder->orderBy('EXPEDIENTEID ASC');
		$query = $builder->get();
		return $query->getResult('array');
	}
	public function get_denunciante($folio, $year)
	{
		$builder = $this->db->table($this->table);
		$builder->select(['*', 'FOLIO.ESTADOID AS FOLIOESTADO', 'FOLIO.MUNICIPIOID AS FOLIOMUNICIPIO', 'DENUNCIANTES.MUNICIPIOID AS DENUNCIANTEMUNICIPIO', 'DENUNCIANTES.ESTADOID AS DENUNCIANTEESTADO', 'DENUNCIANTES.NOMBRE', 'DENUNCIANTES.APELLIDO_PATERNO', 'DENUNCIANTES.APELLIDO_MATERNO']);
		$builder->where('FOLIOID', $folio);
		$builder->where('ANO', $year);
		$builder->join('DENUNCIANTES', 'DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID', 'LEFT');
		$query = $builder->get();
		return $query->getRow();
	}

	public function get_folio_denunciante($denunciante)
	{
		$builder = $this->db->table($this->table);
		$builder->select(['FOLIOID', 'EXPEDIENTEID', 'ANO', 'HECHODELITO']);
		$builder->where('FOLIO.DENUNCIANTEID', $denunciante);
		$builder->join('DENUNCIANTES', 'DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID', 'LEFT');
		$builder->orderBy('FOLIO.FECHAREGISTRO ASC');
		$query = $builder->get();
		return $query->getResult('array');
	}

	public function get_folios_abiertos()
	{
		$builder = $this->db->table($this->table);
		$builder->select(['FOLIO.*', 'DENUNCIANTES.NOMBRE', 'DENUNCIANTES.APELLIDO_PATERNO', 'DENUNCIANTES.APELLIDO_MATERNO']);
		$builder->where('FOLIO.STATUS', 'ABIERTO');
		$builder->where('TIPODENUNCIA !=','ES');
		$builder->join('DENUNCIANTES', 'DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID', 'LEFT');
		$builder->orderBy('FOLIO.FECHAREGISTRO ASC');
		$query = $builder->get();
		return $query->getResult('object');
	}

	public function get_folios_abiertos_escrita()
	{
		$builder = $this->db->table($this->table);
		$builder->select(['FOLIO.*', 'DENUNCIANTES.NOMBRE', 'DENUNCIANTES.APELLIDO_PATERNO', 'DENUNCIANTES.APELLIDO_MATERNO']);
		$builder->where('FOLIO.STATUS', 'ABIERTO');
		$builder->where('TIPODENUNCIA','ES');
		$builder->join('DENUNCIANTES', 'DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID', 'LEFT');
		$builder->orderBy('FOLIO.FECHAREGISTRO ASC');
		$query = $builder->get();
		return $query->getResult('object');
	}

	public function filtro_canalizaciones_derivaciones($bindParams)
	{

		$sql = 'SELECT FO.FOLIOID,FO.ANO, FO.STATUS, FO.HECHOFECHA, MU.MUNICIPIODESCR,
		CONCAT(US.NOMBRE," ",US.APELLIDO_PATERNO," ",US.APELLIDO_MATERNO) AS AGENTE_NOMBRE,FO.EXPEDIENTEID, 
		CONCAT(FPS.NOMBRE," ", FPS.PRIMERAPELLIDO," ", FPS.SEGUNDOAPELLIDO) AS NOMBRE_VTM, DELMOD.DELITOMODALIDADDESCR
		FROM FOLIO AS FO 
		LEFT JOIN MUNICIPIO AS MU ON MU.MUNICIPIOID = FO.MUNICIPIOID
		LEFT JOIN USUARIOS AS US ON US.ID = FO.AGENTEATENCIONID
		LEFT JOIN FOLIOPERSONAFISICA AS FPS ON FPS.FOLIOID = FO.FOLIOID AND FPS.ANO = FO.ANO
		LEFT JOIN FOLIOPERSONAFISIMPDELITO AS FDEL ON FDEL.FOLIOID = FO.FOLIOID AND FDEL.ANO = FO.ANO
		LEFT JOIN DELITOMODALIDAD AS DELMOD ON DELMOD.DELITOMODALIDADID = FDEL.DELITOMODALIDADID
		WHERE MU.ESTADOID = 2 AND FPS.CALIDADJURIDICAID = 1';

		if (!empty($bindParams['MUNICIPIOID'])) $sql = $sql . ' AND MU.MUNICIPIOID = ' . $bindParams['MUNICIPIOID'];
		if (!empty($bindParams['AGENTEATENCIONID'])) $sql = $sql . ' AND US.ID = ' . $bindParams['AGENTEATENCIONID'];
		if (!empty($bindParams['SALIDA'])) $sql = $sql . ' AND FO.STATUS = ' . "'" . $bindParams['SALIDA'] . "'";
		if (empty($bindParams['SALIDA'])) $sql = $sql . ' AND (FO.STATUS = ' . "'CANALIZADO' " . ' OR FO.STATUS = ' . "'DERIVADO') ";

		if (!empty($bindParams['fechaInicio']) && !empty($bindParams['fechaFin'])) $sql = $sql . ' AND FO.HECHOFECHA BETWEEN ' . "'" . $bindParams['fechaInicio'] . "'" . ' AND ' . "'" . $bindParams['fechaFin'] . "'";
		if (!empty($bindParams['fechaInicio']) && empty($bindParams['fechaFin'])) $sql = $sql . ' AND FO.HECHOFECHA BETWEEN ' . "'" . $bindParams['fechaInicio'] . "'" . ' AND ' . "'" . date("Y-m-d") . "'";
		if (empty($bindParams['fechaInicio']) && !empty($bindParams['fechaFin'])) $sql = $sql . ' AND FOD.HECHOFECHA BETWEEN ' . "'" . '2020-01-01' . "'" . ' AND ' . "'" . $bindParams['fechaFin'] . "'";

		if (!empty($bindParams['horaInicio']) && !empty($bindParams['horaFin'])) $sql = $sql . ' AND FO.HECHOHORA BETWEEN ' . "'" . $bindParams['horaInicio'] . "'" . ' AND ' . "'" . $bindParams['horaFin'] . "'";
		if (!empty($bindParams['horaInicio']) && empty($bindParams['horaFin'])) $sql = $sql . ' AND FO.HECHOHORA BETWEEN ' . "'" . $bindParams['horaInicio'] . "':00" . ' AND ' . "'" . '23:59:00' . "'";
		if (empty($bindParams['horaInicio']) && !empty($bindParams['horaFin'])) $sql = $sql . ' AND FO.HECHOHORA BETWEEN ' . "'" . '00:00:00' . "'" . ' AND ' . "'" . $bindParams['horaFin'] . "':00";

		$sql = $sql . ' GROUP BY  FO.FOLIOID, FO.ANO';

		$query = $this->db->query($sql);

		return $query->getResult('object');
	}

	public function filterRegistroAtenciones($obj)
	{
		$strQuery = 'SELECT
		FOLIO.FOLIOID, FOLIO.ANO, FOLIO.EXPEDIENTEID, FOLIO.STATUS, FOLIO.TIPODENUNCIA, FOLIO.FECHAREGISTRO,FOLIO.FECHASALIDA,FOLIO.TIPOEXPEDIENTEID,FOLIO.FECHASALIDA,FOLIO.FECHAREGISTRO, 
		DENUNCIANTES.NOMBRE AS "N_DENUNCIANTE", DENUNCIANTES.APELLIDO_PATERNO AS "APP_DENUNCIANTE", DENUNCIANTES.APELLIDO_MATERNO AS "APM_DENUNCIANTE",DENUNCIANTES.TELEFONO AS "TELEFONODENUNCIANTE",DENUNCIANTES.CORREO AS "CORREODENUNCIANTE",  DENUNCIANTES.SEXO AS "GENERO",		CONCAT(USUARIOS.NOMBRE," ",USUARIOS.APELLIDO_PATERNO," ",USUARIOS.APELLIDO_MATERNO) AS "NOMBRE_AGENTE", 
		USUARIOS.NOMBRE AS "N_AGENT", USUARIOS.APELLIDO_PATERNO AS "APP_AGENT", USUARIOS.APELLIDO_MATERNO AS "APM_AGENT",
		BANDEJARAC.MODULODESCR AS "REMISION_RAC",
		DERIVACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_DERIVACION",
		CANALIZACIONES.INSTITUCIONREMISIONDESCR AS "REMISION_CANALIZACION",
		ESTADO.ESTADODESCR,MUNICIPIO.MUNICIPIODESCR,MUNICIPIOASIGNADO.MUNICIPIODESCR AS MUNICIPIOASIGNADO, TIPOEXPEDIENTE.TIPOEXPEDIENTEDESCR, EMPLEADOS.AREADESCR, TIPOEXPEDIENTE.TIPOEXPEDIENTECLAVE,
		OFICINA.OFICINADESCR AS "OFICINA_EMP" 
		
		FROM FOLIO 
		LEFT JOIN USUARIOS ON USUARIOS.ID = FOLIO.AGENTEATENCIONID
		LEFT JOIN MUNICIPIO AS MUNICIPIOASIGNADO ON MUNICIPIOASIGNADO.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID AND MUNICIPIOASIGNADO.ESTADOID = 2
		LEFT JOIN DENUNCIANTES ON DENUNCIANTES.DENUNCIANTEID = FOLIO.DENUNCIANTEID
		LEFT JOIN TIPOEXPEDIENTE ON TIPOEXPEDIENTE.TIPOEXPEDIENTEID = FOLIO.TIPOEXPEDIENTEID
		LEFT JOIN EMPLEADOS ON EMPLEADOS.EMPLEADOID = FOLIO.AGENTEASIGNADOID AND EMPLEADOS.MUNICIPIOID = FOLIO.MUNICIPIOID
		LEFT JOIN OFICINA ON OFICINA.OFICINAID = FOLIO.OFICINAASIGNADOID AND OFICINA.MUNICIPIOID = FOLIO.MUNICIPIOASIGNADOID
		LEFT JOIN ESTADO ON ESTADO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN MUNICIPIO ON MUNICIPIO.MUNICIPIOID = FOLIO.MUNICIPIOID AND MUNICIPIO.ESTADOID = FOLIO.ESTADOID
		LEFT JOIN BANDEJARAC ON FOLIO.FOLIOID = BANDEJARAC.FOLIOID AND  FOLIO.ANO = BANDEJARAC.ANO
				LEFT JOIN DERIVACIONES ON FOLIO.INSTITUCIONREMISIONID = DERIVACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = DERIVACIONES.MUNICIPIOID
				LEFT JOIN CANALIZACIONES ON FOLIO.INSTITUCIONREMISIONID = CANALIZACIONES.INSTITUCIONREMISIONID AND FOLIO.INSTITUCIONREMISIONMUNICIPIOID = CANALIZACIONES.MUNICIPIOID';

		$fechaInicio = isset($obj['fechaInicio']) ? $obj['fechaInicio'] : '';
		$fechaFin = isset($obj['fechaFin']) ? $obj['fechaFin'] : '';
		$horaInicio = isset($obj['horaInicio']) ? $obj['horaInicio'] : null;
		$horaFin = isset($obj['horaFin']) ? $obj['horaFin'] : null;

		if (isset($obj['fechaInicio'])) {
			unset($obj['fechaInicio']);
		}
		if (isset($obj['fechaFin'])) {
			unset($obj['fechaFin']);
		}
		if (isset($obj['horaInicio'])) {
			unset($obj['horaInicio']);
		}
		if (isset($obj['horaFin'])) {
			unset($obj['horaFin']);
		}

		$count = count($obj);

		if ($count > 0) {
			$strQuery = $strQuery . ' WHERE ';
		}

		foreach ($obj as $clave => $valor) {
			$count -= 1;
			if ($clave != 'fechaInicio' && $clave != 'fechaFin' && $clave != 'horaInicio' && $clave != 'horaFin') {
				$strQuery = $strQuery . 'FOLIO.' . $clave . ' = ' . '"' . $valor . '"';

				if ($count > 0) {
					$strQuery = $strQuery . ' AND ';
				}
			}
		}

		if (count($obj) > 0) {
			$strQuery = $strQuery . ' AND ';
		} else {
			$strQuery = $strQuery . ' WHERE ';
		}

		$strQuery = $strQuery . 'FOLIO.FECHAREGISTRO BETWEEN CAST("' .
			(isset($fechaInicio) ? date("Y-m-d", strtotime($fechaInicio)) : date("Y-m-d")) . ' ' .
			(isset($horaInicio) ? (date('H:i:s', strtotime($horaInicio))) : '00:00:00') . '" AS DATETIME)' . ' AND ' . 'CAST("' .
			(isset($fechaFin) ? (isset($obj['horaFin']) ? date("Y-m-d", strtotime($fechaFin)) : date("Y-m-d", strtotime(date("Y-m-d", strtotime($fechaFin))))) : date("Y-m-d")) . ' ' .
			(isset($horaFin) ? (date('H:i:s', strtotime($horaFin))) : '23:59:59') . '" AS DATETIME)';

		$result = $this->db->query($strQuery)->getResult();

		$dataView = (object)array();
		$dataView->result = $result;
		// $dataView->strQuery = $strQuery;
		return $dataView;
	}
}
