<?php

namespace App\Models;

use CodeIgniter\Model;

class FolioObjetoModel extends Model
{
    protected $table            = 'FOLIOOBJETO';
    protected $allowedFields    = [
        'FOLIOID',
        'ANO',
        'OBJETOID',
        'SITUACION',
        'CLASIFICACIONID',
        'SUBCLASIFICACIONID',
        'MARCA',
        'NUMEROSERIE',
        'CANTIDAD',
        'VALOR',
        'TIPOMONEDAID',
        'DESCRIPCIONDETALLADA',
        'PERSONAFISICAIDPROPIETARIO',
        'PERSONAMORALIDPROPIETARIO',
        'FOTO',
        'PARTICIPAESTADO'
    ];

    public function get_descripcion($folio, $year)
    {
        $sql = 'SELECT FOLIOOBJETO.OBJETOID,FOLIOOBJETO.FOLIOID,FOLIOOBJETO.ANO,FOLIOOBJETO.CLASIFICACIONID,FOLIOOBJETO.SUBCLASIFICACIONID, OBJETOCLASIFICACION.OBJETOCLASIFICACIONDESCR, OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONDESCR
        FROM FOLIOOBJETO
        INNER JOIN OBJETOCLASIFICACION ON OBJETOCLASIFICACION.OBJETOCLASIFICACIONID = FOLIOOBJETO.CLASIFICACIONID
        INNER JOIN OBJETOSUBCLASIFICACION ON OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONID = FOLIOOBJETO.SUBCLASIFICACIONID
        WHERE OBJETOSUBCLASIFICACION.OBJETOCLASIFICACIONID = FOLIOOBJETO.CLASIFICACIONID
        AND FOLIOOBJETO.FOLIOID = ' . $folio . ' AND FOLIOOBJETO.ANO =' . $year;
        $query =  $this->db->query($sql);

        return $query->getResult('array');
    }
    public function get_objetosub($folio, $year, $objetoid, $clasificacion)
    {
        $sql = 'SELECT FOLIOOBJETO.OBJETOID,FOLIOOBJETO.FOLIOID,FOLIOOBJETO.ANO,FOLIOOBJETO.CLASIFICACIONID,FOLIOOBJETO.SUBCLASIFICACIONID, OBJETOSUBCLASIFICACION.OBJETOCLASIFICACIONID,OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONDESCR,OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONID
        FROM FOLIOOBJETO
        INNER JOIN OBJETOSUBCLASIFICACION ON OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONID = FOLIOOBJETO.SUBCLASIFICACIONID
        AND FOLIOOBJETO.FOLIOID = ' . $folio .
            ' AND FOLIOOBJETO.ANO =' . $year .
            ' AND FOLIOOBJETO.OBJETOID =' . $objetoid .
            ' AND OBJETOSUBCLASIFICACION.OBJETOCLASIFICACIONID =' . $clasificacion .
            ' AND OBJETOSUBCLASIFICACION.OBJETOCLASIFICACIONID = FOLIOOBJETO.CLASIFICACIONID' .
            ' AND OBJETOSUBCLASIFICACION.OBJETOSUBCLASIFICACIONID = FOLIOOBJETO.SUBCLASIFICACIONID';

        $query =  $this->db->query($sql);

        // return $query->getRow();
        return $query->getResult('array');
    }
}
