<?php

namespace App\Models;

use CodeIgniter\Model;

class PlantillasModel extends Model
{

	protected $table            = 'PLANTILLAS';
	protected $primaryKey       = 'ID';
	protected $allowedFields    = [
		'ID',
		'TITULO',
		'DESCRIPCION',
		'PLACEHOLDER',
		'TEXTO',
		'PLANTILLAJUSTICIAMEXICALIID',
		'CLASIFICACIONDOCTOMEXICALIID',
		'PLANTILLAJUSTICIATIJUANAID',
		'CLASIFICACIONDOCTOTIJUANAID',
		'PLANTILLAJUSTICIAENSENADAID',
		'CLASIFICACIONDOCTOENSENADAID',
		'AREAPERICIALMEXICALIID',
		'INTERVENCIONMEXICALIID',
		'AREAPERICIALTIJUANAID',
		'INTERVENCIONTIJUANAID',
		'AREAPERICIALENSENADAID',
		'INTERVENCIONENSENADAID',
	];
}
